WHENEVER SQLERROR EXIT SQL.SQLCODE
SET VERIFY OFF

CREATE PROFILE DSO_LIBRARY_PROFILE LIMIT
    FAILED_LOGIN_ATTEMPTS UNLIMITED;

CREATE USER DSO_LIBRARY IDENTIFIED BY "&&reader_password" PROFILE DSO_LIBRARY_PROFILE;

GRANT CREATE SESSION TO DSO_LIBRARY;
GRANT EXECUTE ON DSO_PORTAL.DSO_LIBRARY_CONFIG TO DSO_LIBRARY;

CREATE AUDIT POLICY DSO_LIBRARY_LOGON_FAILURES ACTIONS LOGON;
AUDIT POLICY DSO_LIBRARY_LOGON_FAILURES BY DSO_LIBRARY WHENEVER NOT SUCCESSFUL;

UNDEFINE reader_password
