--liquibase formatted sql

-- Pipelines, their keys and the configuration published for the DevSecOps library.

--changeset dso-portal:002-pipeline dbms:oracle,h2
CREATE TABLE DSO_PIPELINE (
    ID                          NUMBER(19)      GENERATED BY DEFAULT AS IDENTITY,
    SERVICE_ID                  NUMBER(19)      NOT NULL,
    PIPELINE_TYPE               VARCHAR2(20)    NOT NULL,
    AGENT_LABELS                VARCHAR2(1000)  NOT NULL,
    EXTENDED_PIPELINE_JOB       VARCHAR2(500),
    SECURITY_PIPELINE_JOB       VARCHAR2(500),
    JENKINS_JOB                 VARCHAR2(1000),
    DESCRIPTION                 VARCHAR2(1000),
    CREATED_AT                  TIMESTAMP       NOT NULL,
    UPDATED_AT                  TIMESTAMP       NOT NULL,
    VERSION                     NUMBER(19)      DEFAULT 0 NOT NULL,
    CONSTRAINT PK_DSO_PIPELINE PRIMARY KEY (ID),
    CONSTRAINT FK_DSO_PIPELINE_SERVICE FOREIGN KEY (SERVICE_ID) REFERENCES DSO_SERVICE (ID) ON DELETE CASCADE,
    CONSTRAINT UK_DSO_PIPELINE_TYPE UNIQUE (SERVICE_ID, PIPELINE_TYPE),
    CONSTRAINT CK_DSO_PIPELINE_TYPE CHECK (PIPELINE_TYPE IN ('FULL', 'SECURITY', 'EXTENDED', 'SAST'))
);
--rollback DROP TABLE DSO_PIPELINE;

-- One row per key ever issued; a pipeline has at most one ACTIVE key, enforced by the application
-- under a row lock on DSO_PIPELINE. Revoked keys are kept as the audit trail.
--changeset dso-portal:002-pipeline-key dbms:oracle,h2
CREATE TABLE DSO_PIPELINE_KEY (
    ID                          NUMBER(19)      GENERATED BY DEFAULT AS IDENTITY,
    PIPELINE_ID                 NUMBER(19)      NOT NULL,
    KEY_VALUE                   VARCHAR2(36)    NOT NULL,
    STATUS                      VARCHAR2(20)    NOT NULL,
    ISSUED_AT                   TIMESTAMP       NOT NULL,
    REVOKED_AT                  TIMESTAMP,
    REVOKE_REASON               VARCHAR2(500),
    LAST_USED_AT                TIMESTAMP,
    CONSTRAINT PK_DSO_PIPELINE_KEY PRIMARY KEY (ID),
    CONSTRAINT FK_DSO_PIPELINE_KEY_PIPELINE FOREIGN KEY (PIPELINE_ID) REFERENCES DSO_PIPELINE (ID) ON DELETE CASCADE,
    CONSTRAINT UK_DSO_PIPELINE_KEY_VALUE UNIQUE (KEY_VALUE),
    CONSTRAINT CK_DSO_PIPELINE_KEY_STATUS CHECK (
        (STATUS = 'ACTIVE' AND REVOKED_AT IS NULL) OR (STATUS = 'REVOKED' AND REVOKED_AT IS NOT NULL))
);
CREATE INDEX IX_DSO_PIPELINE_KEY_PIPELINE ON DSO_PIPELINE_KEY (PIPELINE_ID, STATUS);
--rollback DROP TABLE DSO_PIPELINE_KEY;

-- The complete configuration of each pipeline as JSON, rendered by the portal whenever the pipeline, its product
-- or the global settings change.
--changeset dso-portal:002-pipeline-config dbms:oracle,h2
CREATE TABLE DSO_PIPELINE_CONFIG (
    PIPELINE_ID                 NUMBER(19)      NOT NULL,
    CONFIG_JSON                 CLOB            NOT NULL,
    RENDERED_AT                 TIMESTAMP       NOT NULL,
    CONSTRAINT PK_DSO_PIPELINE_CONFIG PRIMARY KEY (PIPELINE_ID),
    CONSTRAINT FK_DSO_PIPELINE_CONFIG_PIPELINE FOREIGN KEY (PIPELINE_ID)
        REFERENCES DSO_PIPELINE (ID) ON DELETE CASCADE
);
--rollback DROP TABLE DSO_PIPELINE_CONFIG;

-- What the DevSecOps library reads with its read-only database user: the configuration of the pipeline a key
-- belongs to. A revoked key returns its reason and no configuration.
--changeset dso-portal:002-library-config-view dbms:oracle,h2
CREATE VIEW DSO_LIBRARY_CONFIG_V AS
SELECT k.KEY_VALUE      AS PIPELINE_KEY,
       k.STATUS         AS KEY_STATUS,
       k.REVOKE_REASON  AS REVOKE_REASON,
       c.CONFIG_JSON    AS CONFIG_JSON,
       c.RENDERED_AT    AS RENDERED_AT
  FROM DSO_PIPELINE_KEY k
  LEFT JOIN DSO_PIPELINE_CONFIG c ON c.PIPELINE_ID = k.PIPELINE_ID AND k.STATUS = 'ACTIVE';
--rollback DROP VIEW DSO_LIBRARY_CONFIG_V;
