--liquibase formatted sql

-- The settings every pipeline shares, which services cannot override: one row, created by the portal at start-up
-- with BBH's current values.

--changeset dso-portal:003-global-settings dbms:oracle,h2
CREATE TABLE DSO_GLOBAL_SETTINGS (
    ID                              NUMBER(19)      NOT NULL,
    -- tools and platform
    JENKINS_URL                     VARCHAR2(500),
    JENKINS_LIBRARY                 VARCHAR2(200)   NOT NULL,
    ASOC_URL                        VARCHAR2(500)   NOT NULL,
    APPSCAN_CLIENT_LINUX_URL        VARCHAR2(1000)  NOT NULL,
    APPSCAN_CLIENT_WINDOWS_URL      VARCHAR2(1000)  NOT NULL,
    PROXY_HOST                      VARCHAR2(255),
    PROXY_PORT                      NUMBER(10),
    PROXY_USER                      VARCHAR2(100),
    OIS_HOST                        VARCHAR2(255),
    SONAR_SERVER_URL                VARCHAR2(500)   NOT NULL,
    SONAR_INSTALLATION_NAME         VARCHAR2(200)   NOT NULL,
    NEXUS_IQ_SERVER_URL             VARCHAR2(500)   NOT NULL,
    NEXUS_IQ_CREDENTIALS_ID         VARCHAR2(200)   NOT NULL,
    NEXUS_SNAPSHOT_URL              VARCHAR2(1000),
    NEXUS_SNAPSHOT_REPOSITORY_ID    VARCHAR2(200),
    INFLUX_WRITE_URL                VARCHAR2(1000),
    INFLUX_CREDENTIALS_ID           VARCHAR2(200),
    IOS_BUILD_AGENT                 VARCHAR2(255),
    -- deployment defaults
    UCD_SITE_NAME                   VARCHAR2(200)   NOT NULL,
    UCD_DEPLOY_PROCESS              VARCHAR2(200)   NOT NULL,
    RD_HOST                         VARCHAR2(255)   NOT NULL,
    QC_HOST                         VARCHAR2(255)   NOT NULL,
    SSH_USER                        VARCHAR2(100)   NOT NULL,
    DEPLOY_SCRIPT                   VARCHAR2(500)   NOT NULL,
    VERSION_FILE                    VARCHAR2(500)   NOT NULL,
    -- scan policy (the severity limits are in DSO_GLOBAL_SEVERITY_LIMIT)
    COVERAGE_MIN_LINE               NUMBER(10)      NOT NULL,
    SAST_PREPARE_TIMEOUT_MIN        NUMBER(10)      NOT NULL,
    SAST_POLL_TIMEOUT_MIN           NUMBER(10)      NOT NULL,
    SAST_POLL_INTERVAL_SEC          NUMBER(10)      NOT NULL,
    SCA_ENABLED                     NUMBER(1)       NOT NULL,
    SCA_POLL_TIMEOUT_MIN            NUMBER(10)      NOT NULL,
    SCA_POLL_INTERVAL_SEC           NUMBER(10)      NOT NULL,
    DAST_POLL_TIMEOUT_MIN           NUMBER(10)      NOT NULL,
    DAST_POLL_INTERVAL_SEC          NUMBER(10)      NOT NULL,
    DAST_REPORT_TIMEOUT_MIN         NUMBER(10)      NOT NULL,
    DAST_REPORT_INTERVAL_SEC        NUMBER(10)      NOT NULL,
    SONAR_WAIT_FOR_QUALITY_GATE     NUMBER(1)       NOT NULL,
    SONAR_QUALITY_GATE_TIMEOUT_MIN  NUMBER(10)      NOT NULL,
    -- release gate
    RELEASE_GATE_SCANNERS           VARCHAR2(100),
    RELEASE_GATE_REQUIRE_COVERAGE   NUMBER(1)       NOT NULL,
    RELEASE_GATE_STATE_FILE         VARCHAR2(200)   NOT NULL,
    -- defaults a service may override
    DEFAULT_BUILD_TOOL              VARCHAR2(20)    NOT NULL,
    DEFAULT_DEPLOY_TARGET           VARCHAR2(20)    NOT NULL,
    DEFAULT_SOURCE_DIR              VARCHAR2(500)   NOT NULL,
    TESTS_MAX_PARALLEL              NUMBER(10)      NOT NULL,
    GOLDEN_FIX_ENABLED              NUMBER(1)       NOT NULL,
    GOLDEN_FIX_DIRECT_ONLY          NUMBER(1),
    GOLDEN_FIX_MIN_THREAT_LEVEL     NUMBER(10),
    GOLDEN_FIX_ECOSYSTEMS           VARCHAR2(200),
    GOLDEN_FIX_VERSION_TYPES        VARCHAR2(1000),
    GOLDEN_FIX_EXCLUDE_DIRS         VARCHAR2(2000),
    GOLDEN_FIX_VERIFY               NUMBER(1),
    GOLDEN_FIX_VERIFY_ATTEMPTS      NUMBER(10),
    GOLDEN_FIX_VERIFY_TIMEOUT       NUMBER(10),
    GOLDEN_FIX_VERIFY_MAVEN         VARCHAR2(500),
    GOLDEN_FIX_VERIFY_GRADLE        VARCHAR2(500),
    GOLDEN_FIX_VERIFY_NPM           VARCHAR2(500),
    GOLDEN_FIX_VERIFY_PIP           VARCHAR2(500),
    GOLDEN_FIX_VERIFY_PUB           VARCHAR2(500),
    GOLDEN_FIX_AUTHOR_NAME          VARCHAR2(200),
    GOLDEN_FIX_AUTHOR_EMAIL         VARCHAR2(320),
    GOLDEN_FIX_TIME_ZONE            VARCHAR2(100),
    CREATED_AT                      TIMESTAMP       NOT NULL,
    UPDATED_AT                      TIMESTAMP       NOT NULL,
    VERSION                         NUMBER(19)      DEFAULT 0 NOT NULL,
    CONSTRAINT PK_DSO_GLOBAL_SETTINGS PRIMARY KEY (ID),
    CONSTRAINT CK_DSO_GLOBAL_SETTINGS_ROW CHECK (ID = 1),
    CONSTRAINT CK_DSO_GLOBAL_BUILD_TOOL CHECK (DEFAULT_BUILD_TOOL IN ('GRADLE', 'MAVEN', 'FLUTTER')),
    CONSTRAINT CK_DSO_GLOBAL_DEPLOY_TARGET CHECK (DEFAULT_DEPLOY_TARGET IN ('VM', 'OPENSHIFT')),
    CONSTRAINT CK_DSO_GLOBAL_FLAGS CHECK (SCA_ENABLED IN (0, 1) AND SONAR_WAIT_FOR_QUALITY_GATE IN (0, 1)
        AND RELEASE_GATE_REQUIRE_COVERAGE IN (0, 1) AND GOLDEN_FIX_ENABLED IN (0, 1)
        AND GOLDEN_FIX_DIRECT_ONLY IN (0, 1) AND GOLDEN_FIX_VERIFY IN (0, 1))
);
--rollback DROP TABLE DSO_GLOBAL_SETTINGS;

--changeset dso-portal:003-global-severity-limit dbms:oracle,h2
CREATE TABLE DSO_GLOBAL_SEVERITY_LIMIT (
    SETTINGS_ID                 NUMBER(19)      NOT NULL,
    SCANNER                     VARCHAR2(20)    NOT NULL,
    MAX_CRITICAL                NUMBER(10)      NOT NULL,
    MAX_HIGH                    NUMBER(10)      NOT NULL,
    MAX_MEDIUM                  NUMBER(10)      NOT NULL,
    CONSTRAINT PK_DSO_GLOBAL_SEVERITY_LIMIT PRIMARY KEY (SETTINGS_ID, SCANNER),
    CONSTRAINT FK_DSO_SEVERITY_LIMIT_SETTINGS FOREIGN KEY (SETTINGS_ID)
        REFERENCES DSO_GLOBAL_SETTINGS (ID) ON DELETE CASCADE,
    CONSTRAINT CK_DSO_SEVERITY_LIMIT_SCANNER CHECK (SCANNER IN ('SAST', 'SCA', 'NEXUS_IQ', 'DAST')),
    CONSTRAINT CK_DSO_SEVERITY_LIMIT_VALUES CHECK (MAX_CRITICAL >= 0 AND MAX_HIGH >= 0 AND MAX_MEDIUM >= 0)
);
--rollback DROP TABLE DSO_GLOBAL_SEVERITY_LIMIT;
