--liquibase formatted sql

--changeset dso-portal:005-golden-fix-inherit dbms:oracle
ALTER TABLE DSO_SERVICE MODIFY (GOLDEN_FIX_ENABLED DEFAULT NULL NULL);
--rollback UPDATE DSO_SERVICE SET GOLDEN_FIX_ENABLED = 1 WHERE GOLDEN_FIX_ENABLED IS NULL;
--rollback ALTER TABLE DSO_SERVICE MODIFY (GOLDEN_FIX_ENABLED DEFAULT 1 NOT NULL);

--changeset dso-portal:005-golden-fix-inherit-h2 dbms:h2
ALTER TABLE DSO_SERVICE ALTER COLUMN GOLDEN_FIX_ENABLED SET NULL;
ALTER TABLE DSO_SERVICE ALTER COLUMN GOLDEN_FIX_ENABLED DROP DEFAULT;
--rollback UPDATE DSO_SERVICE SET GOLDEN_FIX_ENABLED = 1 WHERE GOLDEN_FIX_ENABLED IS NULL;
--rollback ALTER TABLE DSO_SERVICE ALTER COLUMN GOLDEN_FIX_ENABLED SET DEFAULT 1;
--rollback ALTER TABLE DSO_SERVICE ALTER COLUMN GOLDEN_FIX_ENABLED SET NOT NULL;
