--liquibase formatted sql

--changeset dso-portal:008-shared-metrics-and-sonar dbms:oracle,h2
ALTER TABLE DSO_SERVICE DROP CONSTRAINT UK_DSO_SERVICE_INFLUX;
ALTER TABLE DSO_SERVICE DROP CONSTRAINT UK_DSO_SERVICE_SONAR_KEY;
--rollback UPDATE DSO_SERVICE s SET INFLUX_PROJECT = SUBSTR(INFLUX_PROJECT, 1, 199 - LENGTH(TO_CHAR(ID))) || '-' || TO_CHAR(ID)
--rollback WHERE EXISTS (SELECT 1 FROM DSO_SERVICE o
--rollback     WHERE o.INFLUX_PROJECT = s.INFLUX_PROJECT AND o.INFLUX_ENV = s.INFLUX_ENV AND o.ID < s.ID);
--rollback UPDATE DSO_SERVICE s SET SONAR_PROJECT_KEY = SUBSTR(SONAR_PROJECT_KEY, 1, 399 - LENGTH(TO_CHAR(ID))) || '-' || TO_CHAR(ID)
--rollback WHERE EXISTS (SELECT 1 FROM DSO_SERVICE o
--rollback     WHERE o.SONAR_PROJECT_KEY = s.SONAR_PROJECT_KEY AND o.ID < s.ID);
--rollback ALTER TABLE DSO_SERVICE ADD CONSTRAINT UK_DSO_SERVICE_INFLUX UNIQUE (INFLUX_PROJECT, INFLUX_ENV);
--rollback ALTER TABLE DSO_SERVICE ADD CONSTRAINT UK_DSO_SERVICE_SONAR_KEY UNIQUE (SONAR_PROJECT_KEY);
