--liquibase formatted sql

--changeset dso-portal:008-shared-metrics-and-sonar dbms:oracle,h2
ALTER TABLE DSO_SERVICE DROP CONSTRAINT UK_DSO_SERVICE_INFLUX;
ALTER TABLE DSO_SERVICE DROP CONSTRAINT UK_DSO_SERVICE_SONAR_KEY;
--rollback ALTER TABLE DSO_SERVICE ADD CONSTRAINT UK_DSO_SERVICE_INFLUX UNIQUE (INFLUX_PROJECT, INFLUX_ENV);
--rollback ALTER TABLE DSO_SERVICE ADD CONSTRAINT UK_DSO_SERVICE_SONAR_KEY UNIQUE (SONAR_PROJECT_KEY);
