--liquibase formatted sql

--changeset dso-portal:012-local-metrics dbms:h2
CREATE TABLE DSO_METRIC_POINT (
    ID                          NUMBER(19)      GENERATED BY DEFAULT AS IDENTITY,
    MEASUREMENT                 VARCHAR2(40)    NOT NULL,
    PROJECT                     VARCHAR2(200)   NOT NULL,
    ENV                         VARCHAR2(50)    NOT NULL,
    JOB                         VARCHAR2(500),
    RECORDED_AT                 TIMESTAMP WITH TIME ZONE NOT NULL,
    POINT_VALUES                VARCHAR2(4000)  NOT NULL,
    CONSTRAINT PK_DSO_METRIC_POINT PRIMARY KEY (ID)
);
CREATE INDEX IX_DSO_METRIC_POINT_SERIES ON DSO_METRIC_POINT (PROJECT, ENV, MEASUREMENT, RECORDED_AT);
--rollback DROP TABLE DSO_METRIC_POINT;
