--liquibase formatted sql

--changeset dso-portal:014-change-profile-fields dbms:oracle,h2
ALTER TABLE DSO_CHANGE_PROFILE RENAME COLUMN TEST_PLAN TO TEST_SUMMARY;
ALTER TABLE DSO_CHANGE_PROFILE ADD (
    RELEASE_NAME                VARCHAR2(100),
    INCIDENT_NUMBER             VARCHAR2(40),
    PROBLEM_NUMBER              VARCHAR2(40),
    AFFECTED_CLIENTS            VARCHAR2(2000),
    L1_MANAGER                  VARCHAR2(200),
    L2_MANAGER                  VARCHAR2(200),
    BUSINESS_APPROVER           VARCHAR2(200),
    DOWNTIME                    NUMBER(1)       DEFAULT 0 NOT NULL,
    TIMING_INSTALLATION_START   VARCHAR2(5),
    TIMING_INSTALLATION_HOURS   NUMBER(10),
    TIMING_VALIDATION_HOURS     NUMBER(10),
    VALIDATION_PLAN             VARCHAR2(2000),
    FIRST_USE_PLAN              VARCHAR2(2000),
    PRIVILEGED_ACCESS_REQUIRED  NUMBER(1)       DEFAULT 0 NOT NULL,
    RISK_BBH_WORKGROUPS         NUMBER(10),
    RISK_BBH_USERS              NUMBER(10),
    RISK_BBH_APPLICATIONS       NUMBER(10),
    RISK_CLIENTS                NUMBER(10),
    RISK_CLIENTS_OUTSIDE_BBH    NUMBER(10),
    RISK_BUSINESS_IMPACT        VARCHAR2(100),
    RISK_CHANGE_COMPLEXITY      VARCHAR2(100),
    RISK_VALIDATION_COMPLEXITY  VARCHAR2(100),
    RISK_BACKOUT_TESTING        VARCHAR2(2000),
    RISK_PLATFORM_STATUS        VARCHAR2(100)
);
UPDATE DSO_CHANGE_PROFILE SET
    L1_MANAGER = REGEXP_SUBSTR(APPROVERS, '[^' || CHR(10) || ']+', 1, 1),
    L2_MANAGER = REGEXP_SUBSTR(APPROVERS, '[^' || CHR(10) || ']+', 1, 2),
    TIMING_INSTALLATION_START = '18:00',
    TIMING_INSTALLATION_HOURS = 2,
    TIMING_VALIDATION_HOURS = 1,
    VALIDATION_PLAN = 'Run the smoke tests of the DevSecOps pipeline against production and check the monitoring of each service.',
    FIRST_USE_PLAN = 'The business owner confirms the first use of the release in production.';
ALTER TABLE DSO_CHANGE_PROFILE MODIFY (TIMING_INSTALLATION_START NOT NULL);
ALTER TABLE DSO_CHANGE_PROFILE MODIFY (TIMING_INSTALLATION_HOURS NOT NULL);
ALTER TABLE DSO_CHANGE_PROFILE MODIFY (TIMING_VALIDATION_HOURS NOT NULL);
ALTER TABLE DSO_CHANGE_PROFILE MODIFY (VALIDATION_PLAN NOT NULL);
ALTER TABLE DSO_CHANGE_PROFILE MODIFY (FIRST_USE_PLAN NOT NULL);
ALTER TABLE DSO_CHANGE_PROFILE ADD CONSTRAINT CK_DSO_CHANGE_PROFILE_FLAGS
    CHECK (DOWNTIME IN (0, 1) AND PRIVILEGED_ACCESS_REQUIRED IN (0, 1));
ALTER TABLE DSO_CHANGE_PROFILE DROP (RISK, IMPACT, RISK_ASSESSMENT, APPROVERS);
--rollback ALTER TABLE DSO_CHANGE_PROFILE ADD (
--rollback     RISK                        VARCHAR2(20)    DEFAULT 'LOW' NOT NULL,
--rollback     IMPACT                      VARCHAR2(20)    DEFAULT 'LOW' NOT NULL,
--rollback     RISK_ASSESSMENT             VARCHAR2(2000)  DEFAULT 'Not recorded' NOT NULL,
--rollback     APPROVERS                   VARCHAR2(2200)  DEFAULT 'Not recorded' NOT NULL
--rollback );
--rollback UPDATE DSO_CHANGE_PROFILE SET APPROVERS = CASE WHEN L2_MANAGER IS NULL THEN L1_MANAGER
--rollback     ELSE L1_MANAGER || CHR(10) || L2_MANAGER END WHERE L1_MANAGER IS NOT NULL;
--rollback ALTER TABLE DSO_CHANGE_PROFILE DROP CONSTRAINT CK_DSO_CHANGE_PROFILE_FLAGS;
--rollback ALTER TABLE DSO_CHANGE_PROFILE DROP (RELEASE_NAME, INCIDENT_NUMBER, PROBLEM_NUMBER, AFFECTED_CLIENTS,
--rollback     L1_MANAGER, L2_MANAGER, BUSINESS_APPROVER, DOWNTIME, TIMING_INSTALLATION_START, TIMING_INSTALLATION_HOURS,
--rollback     TIMING_VALIDATION_HOURS, VALIDATION_PLAN, FIRST_USE_PLAN, PRIVILEGED_ACCESS_REQUIRED, RISK_BBH_WORKGROUPS,
--rollback     RISK_BBH_USERS, RISK_BBH_APPLICATIONS, RISK_CLIENTS, RISK_CLIENTS_OUTSIDE_BBH, RISK_BUSINESS_IMPACT,
--rollback     RISK_CHANGE_COMPLEXITY, RISK_VALIDATION_COMPLEXITY, RISK_BACKOUT_TESTING, RISK_PLATFORM_STATUS);
--rollback ALTER TABLE DSO_CHANGE_PROFILE RENAME COLUMN TEST_SUMMARY TO TEST_PLAN;

--changeset dso-portal:014-production-change-fields dbms:oracle,h2
ALTER TABLE DSO_PRODUCTION_CHANGE RENAME COLUMN PLANNED_START TO INSTALLATION_START;
ALTER TABLE DSO_PRODUCTION_CHANGE RENAME COLUMN PLANNED_END TO INSTALLATION_END;
ALTER TABLE DSO_PRODUCTION_CHANGE RENAME COLUMN TEST_PLAN TO TEST_SUMMARY;
ALTER TABLE DSO_PRODUCTION_CHANGE ADD (
    FIX_VERSION                 VARCHAR2(100),
    VALIDATION_START            TIMESTAMP,
    VALIDATION_END              TIMESTAMP,
    FIRST_USAGE                 TIMESTAMP,
    RELEASE_NAME                VARCHAR2(100),
    INCIDENT_NUMBER             VARCHAR2(40),
    PROBLEM_NUMBER              VARCHAR2(40),
    AFFECTED_CLIENTS            VARCHAR2(2000),
    L1_MANAGER                  VARCHAR2(200),
    L2_MANAGER                  VARCHAR2(200),
    BUSINESS_APPROVER           VARCHAR2(200),
    DOWNTIME                    NUMBER(1)       DEFAULT 0 NOT NULL,
    TIMING_INSTALLATION_START   VARCHAR2(5),
    TIMING_INSTALLATION_HOURS   NUMBER(10),
    TIMING_VALIDATION_HOURS     NUMBER(10),
    VALIDATION_PLAN             VARCHAR2(2000),
    FIRST_USE_PLAN              VARCHAR2(2000),
    PRIVILEGED_ACCESS_REQUIRED  NUMBER(1)       DEFAULT 0 NOT NULL,
    RISK_BBH_WORKGROUPS         NUMBER(10),
    RISK_BBH_USERS              NUMBER(10),
    RISK_BBH_APPLICATIONS       NUMBER(10),
    RISK_CLIENTS                NUMBER(10),
    RISK_CLIENTS_OUTSIDE_BBH    NUMBER(10),
    RISK_BUSINESS_IMPACT        VARCHAR2(100),
    RISK_CHANGE_COMPLEXITY      VARCHAR2(100),
    RISK_VALIDATION_COMPLEXITY  VARCHAR2(100),
    RISK_BACKOUT_TESTING        VARCHAR2(2000),
    RISK_PLATFORM_STATUS        VARCHAR2(100)
);
UPDATE DSO_PRODUCTION_CHANGE SET
    FIX_VERSION = 'Not recorded',
    VALIDATION_START = INSTALLATION_END,
    VALIDATION_END = INSTALLATION_END,
    FIRST_USAGE = INSTALLATION_END,
    L1_MANAGER = REGEXP_SUBSTR(APPROVERS, '[^' || CHR(10) || ']+', 1, 1),
    L2_MANAGER = REGEXP_SUBSTR(APPROVERS, '[^' || CHR(10) || ']+', 1, 2),
    TIMING_INSTALLATION_START = '18:00',
    TIMING_INSTALLATION_HOURS = 2,
    TIMING_VALIDATION_HOURS = 1,
    VALIDATION_PLAN = 'Not recorded',
    FIRST_USE_PLAN = 'Not recorded';
ALTER TABLE DSO_PRODUCTION_CHANGE MODIFY (FIX_VERSION NOT NULL);
ALTER TABLE DSO_PRODUCTION_CHANGE MODIFY (VALIDATION_START NOT NULL);
ALTER TABLE DSO_PRODUCTION_CHANGE MODIFY (VALIDATION_END NOT NULL);
ALTER TABLE DSO_PRODUCTION_CHANGE MODIFY (FIRST_USAGE NOT NULL);
ALTER TABLE DSO_PRODUCTION_CHANGE MODIFY (TIMING_INSTALLATION_START NOT NULL);
ALTER TABLE DSO_PRODUCTION_CHANGE MODIFY (TIMING_INSTALLATION_HOURS NOT NULL);
ALTER TABLE DSO_PRODUCTION_CHANGE MODIFY (TIMING_VALIDATION_HOURS NOT NULL);
ALTER TABLE DSO_PRODUCTION_CHANGE MODIFY (VALIDATION_PLAN NOT NULL);
ALTER TABLE DSO_PRODUCTION_CHANGE MODIFY (FIRST_USE_PLAN NOT NULL);
ALTER TABLE DSO_PRODUCTION_CHANGE ADD CONSTRAINT CK_DSO_PRODUCTION_CHANGE_FLAGS
    CHECK (DOWNTIME IN (0, 1) AND PRIVILEGED_ACCESS_REQUIRED IN (0, 1));
ALTER TABLE DSO_PRODUCTION_CHANGE DROP (RISK, IMPACT, RISK_ASSESSMENT, APPROVERS);
--rollback ALTER TABLE DSO_PRODUCTION_CHANGE ADD (
--rollback     RISK                        VARCHAR2(20)    DEFAULT 'LOW' NOT NULL,
--rollback     IMPACT                      VARCHAR2(20)    DEFAULT 'LOW' NOT NULL,
--rollback     RISK_ASSESSMENT             VARCHAR2(2000)  DEFAULT 'Not recorded' NOT NULL,
--rollback     APPROVERS                   VARCHAR2(2200)  DEFAULT 'Not recorded' NOT NULL
--rollback );
--rollback UPDATE DSO_PRODUCTION_CHANGE SET APPROVERS = CASE WHEN L2_MANAGER IS NULL THEN L1_MANAGER
--rollback     ELSE L1_MANAGER || CHR(10) || L2_MANAGER END WHERE L1_MANAGER IS NOT NULL;
--rollback ALTER TABLE DSO_PRODUCTION_CHANGE DROP CONSTRAINT CK_DSO_PRODUCTION_CHANGE_FLAGS;
--rollback ALTER TABLE DSO_PRODUCTION_CHANGE DROP (FIX_VERSION, VALIDATION_START, VALIDATION_END, FIRST_USAGE,
--rollback     RELEASE_NAME, INCIDENT_NUMBER, PROBLEM_NUMBER, AFFECTED_CLIENTS, L1_MANAGER, L2_MANAGER, BUSINESS_APPROVER,
--rollback     DOWNTIME, TIMING_INSTALLATION_START, TIMING_INSTALLATION_HOURS, TIMING_VALIDATION_HOURS, VALIDATION_PLAN,
--rollback     FIRST_USE_PLAN, PRIVILEGED_ACCESS_REQUIRED, RISK_BBH_WORKGROUPS, RISK_BBH_USERS, RISK_BBH_APPLICATIONS,
--rollback     RISK_CLIENTS, RISK_CLIENTS_OUTSIDE_BBH, RISK_BUSINESS_IMPACT, RISK_CHANGE_COMPLEXITY,
--rollback     RISK_VALIDATION_COMPLEXITY, RISK_BACKOUT_TESTING, RISK_PLATFORM_STATUS);
--rollback ALTER TABLE DSO_PRODUCTION_CHANGE RENAME COLUMN TEST_SUMMARY TO TEST_PLAN;
--rollback ALTER TABLE DSO_PRODUCTION_CHANGE RENAME COLUMN INSTALLATION_END TO PLANNED_END;
--rollback ALTER TABLE DSO_PRODUCTION_CHANGE RENAME COLUMN INSTALLATION_START TO PLANNED_START;

--changeset dso-portal:014-privileged-users dbms:oracle,h2
CREATE TABLE DSO_CHANGE_PROFILE_PRIVILEGED_USER (
    PROFILE_ID                  NUMBER(19)      NOT NULL,
    POSITION                    NUMBER(10)      NOT NULL,
    USER_NAME                   VARCHAR2(200)   NOT NULL,
    ACCOUNT_NAME                VARCHAR2(200)   NOT NULL,
    CONSTRAINT PK_DSO_CHANGE_PROFILE_PRIV_USER PRIMARY KEY (PROFILE_ID, POSITION),
    CONSTRAINT FK_DSO_CHANGE_PROFILE_PRIV_USER FOREIGN KEY (PROFILE_ID)
        REFERENCES DSO_CHANGE_PROFILE (ID) ON DELETE CASCADE
);
CREATE TABLE DSO_PRODUCTION_CHANGE_PRIVILEGED_USER (
    CHANGE_ID                   NUMBER(19)      NOT NULL,
    POSITION                    NUMBER(10)      NOT NULL,
    USER_NAME                   VARCHAR2(200)   NOT NULL,
    ACCOUNT_NAME                VARCHAR2(200)   NOT NULL,
    CONSTRAINT PK_DSO_PRODUCTION_CHANGE_PRIV_USER PRIMARY KEY (CHANGE_ID, POSITION),
    CONSTRAINT FK_DSO_PRODUCTION_CHANGE_PRIV_USER FOREIGN KEY (CHANGE_ID)
        REFERENCES DSO_PRODUCTION_CHANGE (ID) ON DELETE CASCADE
);
--rollback DROP TABLE DSO_PRODUCTION_CHANGE_PRIVILEGED_USER;
--rollback DROP TABLE DSO_CHANGE_PROFILE_PRIVILEGED_USER;
