--liquibase formatted sql

--changeset dso-portal:016-change-profile-task dbms:oracle,h2
CREATE TABLE DSO_CHANGE_PROFILE_TASK (
    PROFILE_ID                  NUMBER(19)      NOT NULL,
    POSITION                    NUMBER(10)      NOT NULL,
    SHORT_DESCRIPTION           VARCHAR2(160)   NOT NULL,
    DESCRIPTION                 VARCHAR2(4000)  NOT NULL,
    CONSTRAINT PK_DSO_CHANGE_PROFILE_TASK PRIMARY KEY (PROFILE_ID, POSITION),
    CONSTRAINT FK_DSO_CHANGE_PROFILE_TASK FOREIGN KEY (PROFILE_ID)
        REFERENCES DSO_CHANGE_PROFILE (ID) ON DELETE CASCADE
);
--rollback DROP TABLE DSO_CHANGE_PROFILE_TASK;

--changeset dso-portal:016-change-profile-task-defaults dbms:oracle
INSERT INTO DSO_CHANGE_PROFILE_TASK (PROFILE_ID, POSITION, SHORT_DESCRIPTION, DESCRIPTION)
SELECT p.ID, ROW_NUMBER() OVER (PARTITION BY p.ID ORDER BY s.DISPLAY_ORDER, s.ID) - 1,
       SUBSTRB('Deploy ' || s.NAME || ' of ' || pr.NAME || ' to production', 1, 160),
       'Deploy ' || s.NAME || ' of ' || pr.NAME || ', then run its smoke tests and confirm the result in this task.'
  FROM DSO_CHANGE_PROFILE p
  JOIN DSO_PRODUCT pr ON pr.ID = p.PRODUCT_ID
  JOIN DSO_SERVICE s ON s.PRODUCT_ID = pr.ID;
INSERT INTO DSO_CHANGE_PROFILE_TASK (PROFILE_ID, POSITION, SHORT_DESCRIPTION, DESCRIPTION)
SELECT p.ID, 0, SUBSTRB('Deploy ' || pr.NAME || ' to production', 1, 160),
       'Deploy the release of ' || pr.NAME || ' in the change window with its deployment jobs, then run the smoke tests of the DevSecOps pipeline and record the result in this task.'
  FROM DSO_CHANGE_PROFILE p
  JOIN DSO_PRODUCT pr ON pr.ID = p.PRODUCT_ID
 WHERE NOT EXISTS (SELECT 1 FROM DSO_SERVICE s WHERE s.PRODUCT_ID = pr.ID);
INSERT INTO DSO_CHANGE_PROFILE_TASK (PROFILE_ID, POSITION, SHORT_DESCRIPTION, DESCRIPTION)
SELECT p.ID, 1, SUBSTRB('Validate ' || pr.NAME || ' in production', 1, 160),
       'Run the post-install validation of ' || pr.NAME || ': the smoke tests and the monitoring, then confirm the release with the business owner in this task.'
  FROM DSO_CHANGE_PROFILE p
  JOIN DSO_PRODUCT pr ON pr.ID = p.PRODUCT_ID
 WHERE NOT EXISTS (SELECT 1 FROM DSO_SERVICE s WHERE s.PRODUCT_ID = pr.ID);
--rollback DELETE FROM DSO_CHANGE_PROFILE_TASK;

--changeset dso-portal:016-change-profile-task-defaults-h2 dbms:h2
INSERT INTO DSO_CHANGE_PROFILE_TASK (PROFILE_ID, POSITION, SHORT_DESCRIPTION, DESCRIPTION)
SELECT p.ID, ROW_NUMBER() OVER (PARTITION BY p.ID ORDER BY s.DISPLAY_ORDER, s.ID) - 1,
       SUBSTR('Deploy ' || s.NAME || ' of ' || pr.NAME || ' to production', 1, 160),
       'Deploy ' || s.NAME || ' of ' || pr.NAME || ', then run its smoke tests and confirm the result in this task.'
  FROM DSO_CHANGE_PROFILE p
  JOIN DSO_PRODUCT pr ON pr.ID = p.PRODUCT_ID
  JOIN DSO_SERVICE s ON s.PRODUCT_ID = pr.ID;
INSERT INTO DSO_CHANGE_PROFILE_TASK (PROFILE_ID, POSITION, SHORT_DESCRIPTION, DESCRIPTION)
SELECT p.ID, 0, SUBSTR('Deploy ' || pr.NAME || ' to production', 1, 160),
       'Deploy the release of ' || pr.NAME || ' in the change window with its deployment jobs, then run the smoke tests of the DevSecOps pipeline and record the result in this task.'
  FROM DSO_CHANGE_PROFILE p
  JOIN DSO_PRODUCT pr ON pr.ID = p.PRODUCT_ID
 WHERE NOT EXISTS (SELECT 1 FROM DSO_SERVICE s WHERE s.PRODUCT_ID = pr.ID);
INSERT INTO DSO_CHANGE_PROFILE_TASK (PROFILE_ID, POSITION, SHORT_DESCRIPTION, DESCRIPTION)
SELECT p.ID, 1, SUBSTR('Validate ' || pr.NAME || ' in production', 1, 160),
       'Run the post-install validation of ' || pr.NAME || ': the smoke tests and the monitoring, then confirm the release with the business owner in this task.'
  FROM DSO_CHANGE_PROFILE p
  JOIN DSO_PRODUCT pr ON pr.ID = p.PRODUCT_ID
 WHERE NOT EXISTS (SELECT 1 FROM DSO_SERVICE s WHERE s.PRODUCT_ID = pr.ID);
--rollback DELETE FROM DSO_CHANGE_PROFILE_TASK;

--changeset dso-portal:016-production-change-sync dbms:oracle,h2
ALTER TABLE DSO_PRODUCTION_CHANGE ADD (
    DEPARTMENT_ID               NUMBER(19),
    STATE                       VARCHAR2(30)    DEFAULT 'DRAFT' NOT NULL,
    SYNCED_AT                   TIMESTAMP,
    UPDATE_STATUS               VARCHAR2(20),
    UPDATE_REQUESTED_AT         TIMESTAMP,
    UPDATE_DEPARTMENT           VARCHAR2(100),
    UPDATE_FIELDS               VARCHAR2(1000),
    UPDATE_MESSAGE              VARCHAR2(1000),
    UPDATE_CHECKED_AT           TIMESTAMP
);
UPDATE DSO_PRODUCTION_CHANGE c
   SET DEPARTMENT_ID = COALESCE((SELECT d.ID FROM DSO_DEPARTMENT d WHERE d.NAME = c.DEPARTMENT_NAME),
                                (SELECT p.DEPARTMENT_ID FROM DSO_PRODUCT p WHERE p.ID = c.PRODUCT_ID));
CREATE INDEX IX_DSO_PRODUCTION_CHANGE_DEPARTMENT ON DSO_PRODUCTION_CHANGE (DEPARTMENT_ID);
ALTER TABLE DSO_PRODUCTION_CHANGE ADD CONSTRAINT FK_DSO_PRODUCTION_CHANGE_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID)
    REFERENCES DSO_DEPARTMENT (ID) ON DELETE SET NULL;
ALTER TABLE DSO_PRODUCTION_CHANGE ADD CONSTRAINT CK_DSO_PRODUCTION_CHANGE_STATE CHECK (STATE IN ('DRAFT',
    'BUSINESS_APPROVAL', 'PRIMARY_APPROVAL', 'SECONDARY_APPROVAL', 'CTASK_APPROVAL', 'ESCALATED_APPROVAL',
    'IMPLEMENTATION', 'CLOSED'));
ALTER TABLE DSO_PRODUCTION_CHANGE ADD CONSTRAINT CK_DSO_PRODUCTION_CHANGE_UPDATE
    CHECK (UPDATE_STATUS IN ('PENDING', 'APPLIED', 'NOT_APPLIED'));
--rollback ALTER TABLE DSO_PRODUCTION_CHANGE DROP CONSTRAINT CK_DSO_PRODUCTION_CHANGE_UPDATE;
--rollback ALTER TABLE DSO_PRODUCTION_CHANGE DROP CONSTRAINT CK_DSO_PRODUCTION_CHANGE_STATE;
--rollback ALTER TABLE DSO_PRODUCTION_CHANGE DROP CONSTRAINT FK_DSO_PRODUCTION_CHANGE_DEPARTMENT;
--rollback DROP INDEX IX_DSO_PRODUCTION_CHANGE_DEPARTMENT;
--rollback ALTER TABLE DSO_PRODUCTION_CHANGE DROP (DEPARTMENT_ID, STATE, SYNCED_AT, UPDATE_STATUS, UPDATE_REQUESTED_AT,
--rollback     UPDATE_DEPARTMENT, UPDATE_FIELDS, UPDATE_MESSAGE, UPDATE_CHECKED_AT);

--changeset dso-portal:016-production-change-stage dbms:oracle,h2
CREATE TABLE DSO_PRODUCTION_CHANGE_STAGE (
    CHANGE_ID                   NUMBER(19)      NOT NULL,
    POSITION                    NUMBER(10)      NOT NULL,
    STAGE                       VARCHAR2(30)    NOT NULL,
    ENTERED_AT                  TIMESTAMP       NOT NULL,
    CONSTRAINT PK_DSO_PRODUCTION_CHANGE_STAGE PRIMARY KEY (CHANGE_ID, POSITION),
    CONSTRAINT FK_DSO_PRODUCTION_CHANGE_STAGE FOREIGN KEY (CHANGE_ID)
        REFERENCES DSO_PRODUCTION_CHANGE (ID) ON DELETE CASCADE,
    CONSTRAINT CK_DSO_PRODUCTION_CHANGE_STAGE CHECK (STAGE IN ('DRAFT', 'BUSINESS_APPROVAL', 'PRIMARY_APPROVAL',
        'SECONDARY_APPROVAL', 'CTASK_APPROVAL', 'ESCALATED_APPROVAL', 'IMPLEMENTATION', 'CLOSED'))
);
INSERT INTO DSO_PRODUCTION_CHANGE_STAGE (CHANGE_ID, POSITION, STAGE, ENTERED_AT)
SELECT ID, 0, 'DRAFT', CREATED_AT FROM DSO_PRODUCTION_CHANGE;
--rollback DROP TABLE DSO_PRODUCTION_CHANGE_STAGE;

--changeset dso-portal:016-production-change-task-state dbms:oracle,h2
ALTER TABLE DSO_PRODUCTION_CHANGE_TASK DROP COLUMN SERVICE_NAME;
ALTER TABLE DSO_PRODUCTION_CHANGE_TASK MODIFY (TASK_NUMBER NULL);
ALTER TABLE DSO_PRODUCTION_CHANGE_TASK ADD (STATE VARCHAR2(20) DEFAULT 'OPEN' NOT NULL);
ALTER TABLE DSO_PRODUCTION_CHANGE_TASK ADD CONSTRAINT CK_DSO_PRODUCTION_CHANGE_TASK_STATE
    CHECK (STATE IN ('OPEN', 'WORK_IN_PROGRESS', 'CLOSED', 'CANCELED'));
--rollback ALTER TABLE DSO_PRODUCTION_CHANGE_TASK DROP CONSTRAINT CK_DSO_PRODUCTION_CHANGE_TASK_STATE;
--rollback ALTER TABLE DSO_PRODUCTION_CHANGE_TASK DROP COLUMN STATE;
--rollback DELETE FROM DSO_PRODUCTION_CHANGE_TASK WHERE TASK_NUMBER IS NULL;
--rollback ALTER TABLE DSO_PRODUCTION_CHANGE_TASK MODIFY (TASK_NUMBER NOT NULL);
--rollback ALTER TABLE DSO_PRODUCTION_CHANGE_TASK ADD (SERVICE_NAME VARCHAR2(100));
--rollback UPDATE DSO_PRODUCTION_CHANGE_TASK SET SERVICE_NAME = 'Not recorded';
--rollback ALTER TABLE DSO_PRODUCTION_CHANGE_TASK MODIFY (SERVICE_NAME NOT NULL);
