--liquibase formatted sql

--changeset dso-portal:020-change-flags-h2 dbms:h2
ALTER TABLE DSO_CHANGE_PROFILE DROP CONSTRAINT CK_DSO_CHANGE_PROFILE_FLAGS;
ALTER TABLE DSO_CHANGE_PROFILE ADD CONSTRAINT CK_DSO_CHANGE_PROFILE_FLAGS
    CHECK (DOWNTIME IN (0, 1) AND PRIVILEGED_ACCESS_REQUIRED IN (0, 1));
ALTER TABLE DSO_PRODUCTION_CHANGE DROP CONSTRAINT CK_DSO_PRODUCTION_CHANGE_FLAGS;
ALTER TABLE DSO_PRODUCTION_CHANGE ADD CONSTRAINT CK_DSO_PRODUCTION_CHANGE_FLAGS
    CHECK (DOWNTIME IN (0, 1) AND PRIVILEGED_ACCESS_REQUIRED IN (0, 1));
--rollback empty
