--liquibase formatted sql

--changeset dso-portal:021-drop-product-description dbms:oracle,h2
ALTER TABLE DSO_CHANGE_PROFILE DROP COLUMN DESCRIPTION;
ALTER TABLE DSO_PRODUCTION_CHANGE DROP COLUMN PRODUCT_DESCRIPTION;
--rollback ALTER TABLE DSO_PRODUCTION_CHANGE ADD (PRODUCT_DESCRIPTION VARCHAR2(2000));
--rollback ALTER TABLE DSO_CHANGE_PROFILE ADD (DESCRIPTION VARCHAR2(2000));

--changeset dso-portal:021-change-flags-h2 dbms:h2
ALTER TABLE DSO_CHANGE_PROFILE DROP CONSTRAINT CK_DSO_CHANGE_PROFILE_FLAGS;
ALTER TABLE DSO_CHANGE_PROFILE ADD CONSTRAINT CK_DSO_CHANGE_PROFILE_FLAGS
    CHECK (DOWNTIME IN (0, 1) AND PRIVILEGED_ACCESS_REQUIRED IN (0, 1));
ALTER TABLE DSO_PRODUCTION_CHANGE DROP CONSTRAINT CK_DSO_PRODUCTION_CHANGE_FLAGS;
ALTER TABLE DSO_PRODUCTION_CHANGE ADD CONSTRAINT CK_DSO_PRODUCTION_CHANGE_FLAGS
    CHECK (DOWNTIME IN (0, 1) AND PRIVILEGED_ACCESS_REQUIRED IN (0, 1));
--rollback empty
