--liquibase formatted sql

--changeset dso-portal:024-drop-sca-scan-settings dbms:oracle,h2
ALTER TABLE DSO_GLOBAL_SETTINGS DROP CONSTRAINT CK_DSO_GLOBAL_FLAGS;
ALTER TABLE DSO_GLOBAL_SETTINGS DROP (SCA_ENABLED, SCA_POLL_TIMEOUT_MIN, SCA_POLL_INTERVAL_SEC);
ALTER TABLE DSO_GLOBAL_SETTINGS ADD CONSTRAINT CK_DSO_GLOBAL_FLAGS CHECK (SONAR_WAIT_FOR_QUALITY_GATE IN (0, 1)
    AND RELEASE_GATE_REQUIRE_COVERAGE IN (0, 1) AND GOLDEN_FIX_ENABLED IN (0, 1)
    AND GOLDEN_FIX_DIRECT_ONLY IN (0, 1) AND GOLDEN_FIX_VERIFY IN (0, 1));
--rollback ALTER TABLE DSO_GLOBAL_SETTINGS DROP CONSTRAINT CK_DSO_GLOBAL_FLAGS;
--rollback ALTER TABLE DSO_GLOBAL_SETTINGS ADD (SCA_ENABLED NUMBER(1) DEFAULT 1 NOT NULL,
--rollback     SCA_POLL_TIMEOUT_MIN NUMBER(10) DEFAULT 40 NOT NULL, SCA_POLL_INTERVAL_SEC NUMBER(10) DEFAULT 30 NOT NULL);
--rollback ALTER TABLE DSO_GLOBAL_SETTINGS ADD CONSTRAINT CK_DSO_GLOBAL_FLAGS CHECK (SCA_ENABLED IN (0, 1)
--rollback     AND SONAR_WAIT_FOR_QUALITY_GATE IN (0, 1) AND RELEASE_GATE_REQUIRE_COVERAGE IN (0, 1)
--rollback     AND GOLDEN_FIX_ENABLED IN (0, 1) AND GOLDEN_FIX_DIRECT_ONLY IN (0, 1) AND GOLDEN_FIX_VERIFY IN (0, 1));
