--liquibase formatted sql

--changeset dso-portal:025-secure-coding-ticket dbms:oracle,h2
ALTER TABLE DSO_CHANGE_PROFILE ADD (
    APO_NUMBER                  VARCHAR2(40),
    BITBUCKET_URL               VARCHAR2(500),
    ARTIFACT_LINK               VARCHAR2(500),
    QC_APPLICATION_LINK         VARCHAR2(500)
);
ALTER TABLE DSO_PRODUCTION_CHANGE ADD (
    APO_NUMBER                  VARCHAR2(40),
    BITBUCKET_URL               VARCHAR2(500),
    ARTIFACT_LINK               VARCHAR2(500),
    QC_APPLICATION_LINK         VARCHAR2(500)
);
UPDATE DSO_CHANGE_PROFILE SET SECURE_CODING_TICKET = NULL;
--rollback ALTER TABLE DSO_PRODUCTION_CHANGE DROP (APO_NUMBER, BITBUCKET_URL, ARTIFACT_LINK, QC_APPLICATION_LINK);
--rollback ALTER TABLE DSO_CHANGE_PROFILE DROP (APO_NUMBER, BITBUCKET_URL, ARTIFACT_LINK, QC_APPLICATION_LINK);

--changeset dso-portal:025-change-flags-h2 dbms:h2
ALTER TABLE DSO_CHANGE_PROFILE DROP CONSTRAINT CK_DSO_CHANGE_PROFILE_FLAGS;
ALTER TABLE DSO_CHANGE_PROFILE ADD CONSTRAINT CK_DSO_CHANGE_PROFILE_FLAGS
    CHECK (DOWNTIME IN (0, 1) AND PRIVILEGED_ACCESS_REQUIRED IN (0, 1));
ALTER TABLE DSO_PRODUCTION_CHANGE DROP CONSTRAINT CK_DSO_PRODUCTION_CHANGE_FLAGS;
ALTER TABLE DSO_PRODUCTION_CHANGE ADD CONSTRAINT CK_DSO_PRODUCTION_CHANGE_FLAGS
    CHECK (DOWNTIME IN (0, 1) AND PRIVILEGED_ACCESS_REQUIRED IN (0, 1));
--rollback empty
