spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        type:
          preferred_instant_jdbc_type: TIMESTAMP
          preferred_boolean_jdbc_type: INTEGER
        default_batch_fetch_size: 50
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    analytics-enabled: false
  web:
    resources:
      cache:
        cachecontrol:
          no-cache: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
