org.gradle.console=rich
org.gradle.logging.level=info
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8

npm.registry=http://tools.bbh.com/nexus/repository/npm-group
npm.strictSsl=false
npm.cafile=/etc/ssl/certs/bbh-ca.pem

systemProp.http.proxyHost=njproxy
systemProp.http.proxyPort=9090
systemProp.http.nonProxyHosts=localhost|*.bbh.com

systemProp.https.proxyHost=njproxy
systemProp.https.proxyPort=9090
systemProp.https.nonProxyHosts=localhost|*.bbh.com

npm.http.proxy=http://njproxy:9090
npm.https.proxy=http://njproxy:9090

npm.no.proxy=localhost,127.0.0.1,*.testbbh.com,*.bbh.com,tools.bbh.com

npm.loglevel=verbose

npm.executable=C:\\Program Files\\nodejs\\npm.cmd
npx.executable=C:\\Program Files\\nodejs\\npx.cmd

nexus.releasesUrl=https://tools.bbh.com/nexus/repository/maven-releases/
nexus.snapshotsUrl=https://tools.bbh.com/nexus/repository/maven-snapshots/
