pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

dependencyResolutionManagement {
    repositoriesMode = RepositoriesMode.FAIL_ON_PROJECT_REPOS
    repositories {
        mavenCentral()
        ivy {
            name = 'Node.js'
            url = providers.gradleProperty('nodeDistBaseUrl').getOrElse('https://nodejs.org/dist/')
            patternLayout {
                artifact 'v[revision]/[artifact](-v[revision]-[classifier]).[ext]'
            }
            metadataSources {
                artifact()
            }
            content {
                includeModule('org.nodejs', 'node')
            }
        }
    }
}

rootProject.name = 'dso-portal'

include 'gui', 'backend'
