pluginManagement {
    repositories {
        if (providers.gradleProperty('bbhNetwork').getOrElse('true') != 'false') {
            maven { url = 'https://tools.bbh.com/nexus/content/groups/public' }
            maven { url = uri("https://tools.bbh.com/nexus/repository/gradle-plugins/") }
            maven { url = uri("https://tools.bbh.com/nexus/repository/maven-public/") }
        }
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode = RepositoriesMode.FAIL_ON_PROJECT_REPOS
    repositories {
        if (providers.gradleProperty('bbhNetwork').getOrElse('true') != 'false') {
            maven {
                url = uri("http://tools.bbh.com/nexus/content/groups/public")
                allowInsecureProtocol = true
            }
            maven { url = uri("https://tools.bbh.com/nexus/repository/gradle-plugins/") }
            maven { url = uri("https://tools.bbh.com/nexus/repository/maven-public/") }
            maven { url = uri("https://tools.bbh.com/nexus/repository/maven-central/") }
        } else {
            mavenCentral()
        }
    }
}

rootProject.name = 'dso-portal'

include 'backend', 'frontend'
