apiVersion: 1

datasources:
  - name: DORA-metrics
    uid: dso-influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: DevSecOps
      defaultBucket: DORA-metrics
    secureJsonData:
      token: $INFLUX_TOKEN
