-- DevSecOps management portal schema for MySQL 8.0.16 and later (local runs).
-- Mirrors db/migration/oracle/V1__create_catalog_and_pipelines.sql; keep the two in step.

CREATE TABLE DSO_PRODUCT (
    ID                          BIGINT          NOT NULL AUTO_INCREMENT,
    CODE                        VARCHAR(50)     NOT NULL,
    NAME                        VARCHAR(200)    NOT NULL,
    DESCRIPTION                 VARCHAR(4000),
    OWNER_TEAM                  VARCHAR(200),
    CONTACT_EMAIL               VARCHAR(320),
    ASOC_KEY_ID                 VARCHAR(200)    NOT NULL,
    ASOC_SECRET_CREDENTIALS_ID  VARCHAR(200),
    CREATED_AT                  DATETIME(6)     NOT NULL,
    UPDATED_AT                  DATETIME(6)     NOT NULL,
    VERSION                     BIGINT          NOT NULL DEFAULT 0,
    CONSTRAINT PK_DSO_PRODUCT PRIMARY KEY (ID),
    CONSTRAINT UK_DSO_PRODUCT_CODE UNIQUE (CODE),
    CONSTRAINT UK_DSO_PRODUCT_NAME UNIQUE (NAME)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE DSO_SERVICE (
    ID                          BIGINT          NOT NULL AUTO_INCREMENT,
    PRODUCT_ID                  BIGINT          NOT NULL,
    NAME                        VARCHAR(100)    NOT NULL,
    DESCRIPTION                 VARCHAR(2000),
    DISPLAY_ORDER               INT             NOT NULL DEFAULT 0,
    BUILD_TOOL                  VARCHAR(20)     NOT NULL,
    DEPLOY_TARGET               VARCHAR(20)     NOT NULL,
    SOURCE_DIR                  VARCHAR(500)    NOT NULL DEFAULT '.',
    JAVA_PATH                   VARCHAR(500),
    BUILD_TOOL_AUTO_SETUP       INT             NOT NULL DEFAULT 0,
    APPSCAN_APP_ID              VARCHAR(36)     NOT NULL,
    SAST_SCAN_NAME              VARCHAR(200),
    DAST_ENABLED                INT             NOT NULL DEFAULT 0,
    DAST_TARGET_URL             VARCHAR(1000),
    DAST_PRESENCE_ID            VARCHAR(100),
    SONAR_PROJECT_NAME          VARCHAR(200),
    SONAR_PROJECT_KEY           VARCHAR(400),
    NEXUS_IQ_APPLICATION        VARCHAR(200),
    NEXUS_IQ_SCAN_PATTERNS      VARCHAR(2000),
    REPOSITORY_URL              VARCHAR(1000),
    BITBUCKET_CREDENTIALS_ID    VARCHAR(200),
    GOLDEN_FIX_ENABLED          INT             NOT NULL DEFAULT 1,
    METRICS_ENABLED             INT             NOT NULL DEFAULT 1,
    INFLUX_PROJECT              VARCHAR(200)    NOT NULL,
    INFLUX_ENV                  VARCHAR(50)     NOT NULL DEFAULT 'test',
    APP_NAME                    VARCHAR(200),
    ARTIFACT_NAME               VARCHAR(300),
    ADDITIONAL_CONFIG           LONGTEXT,
    CREATED_AT                  DATETIME(6)     NOT NULL,
    UPDATED_AT                  DATETIME(6)     NOT NULL,
    VERSION                     BIGINT          NOT NULL DEFAULT 0,
    CONSTRAINT PK_DSO_SERVICE PRIMARY KEY (ID),
    CONSTRAINT FK_DSO_SERVICE_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES DSO_PRODUCT (ID) ON DELETE CASCADE,
    CONSTRAINT UK_DSO_SERVICE_NAME UNIQUE (PRODUCT_ID, NAME),
    CONSTRAINT UK_DSO_SERVICE_INFLUX UNIQUE (INFLUX_PROJECT, INFLUX_ENV),
    CONSTRAINT UK_DSO_SERVICE_SONAR_KEY UNIQUE (SONAR_PROJECT_KEY),
    CONSTRAINT CK_DSO_SERVICE_BUILD_TOOL CHECK (BUILD_TOOL IN ('GRADLE', 'MAVEN', 'FLUTTER')),
    CONSTRAINT CK_DSO_SERVICE_DEPLOY_TARGET CHECK (DEPLOY_TARGET IN ('VM', 'OPENSHIFT')),
    CONSTRAINT CK_DSO_SERVICE_FLAGS CHECK (BUILD_TOOL_AUTO_SETUP IN (0, 1) AND DAST_ENABLED IN (0, 1)
        AND GOLDEN_FIX_ENABLED IN (0, 1) AND METRICS_ENABLED IN (0, 1)),
    CONSTRAINT CK_DSO_SERVICE_DAST CHECK (DAST_ENABLED = 0 OR DAST_TARGET_URL IS NOT NULL)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE DSO_PIPELINE (
    ID                          BIGINT          NOT NULL AUTO_INCREMENT,
    SERVICE_ID                  BIGINT          NOT NULL,
    PIPELINE_TYPE               VARCHAR(20)     NOT NULL,
    AGENT_LABELS                VARCHAR(1000)   NOT NULL,
    EXTENDED_PIPELINE_JOB       VARCHAR(500),
    DESCRIPTION                 VARCHAR(1000),
    CREATED_AT                  DATETIME(6)     NOT NULL,
    UPDATED_AT                  DATETIME(6)     NOT NULL,
    VERSION                     BIGINT          NOT NULL DEFAULT 0,
    CONSTRAINT PK_DSO_PIPELINE PRIMARY KEY (ID),
    CONSTRAINT FK_DSO_PIPELINE_SERVICE FOREIGN KEY (SERVICE_ID) REFERENCES DSO_SERVICE (ID) ON DELETE CASCADE,
    CONSTRAINT UK_DSO_PIPELINE_TYPE UNIQUE (SERVICE_ID, PIPELINE_TYPE),
    CONSTRAINT CK_DSO_PIPELINE_TYPE CHECK (PIPELINE_TYPE IN ('FULL', 'SECURITY', 'EXTENDED', 'SAST'))
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE DSO_PIPELINE_KEY (
    ID                          BIGINT          NOT NULL AUTO_INCREMENT,
    PIPELINE_ID                 BIGINT          NOT NULL,
    KEY_VALUE                   VARCHAR(36)     NOT NULL,
    STATUS                      VARCHAR(20)     NOT NULL,
    ISSUED_AT                   DATETIME(6)     NOT NULL,
    REVOKED_AT                  DATETIME(6),
    REVOKE_REASON               VARCHAR(500),
    LAST_USED_AT                DATETIME(6),
    CONSTRAINT PK_DSO_PIPELINE_KEY PRIMARY KEY (ID),
    CONSTRAINT FK_DSO_PIPELINE_KEY_PIPELINE FOREIGN KEY (PIPELINE_ID) REFERENCES DSO_PIPELINE (ID) ON DELETE CASCADE,
    CONSTRAINT UK_DSO_PIPELINE_KEY_VALUE UNIQUE (KEY_VALUE),
    CONSTRAINT CK_DSO_PIPELINE_KEY_STATUS CHECK (
        (STATUS = 'ACTIVE' AND REVOKED_AT IS NULL) OR (STATUS = 'REVOKED' AND REVOKED_AT IS NOT NULL))
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE INDEX IX_DSO_PIPELINE_KEY_PIPELINE ON DSO_PIPELINE_KEY (PIPELINE_ID, STATUS);
