--liquibase formatted sql

--changeset dso-portal:009-nexus-iq-applications dbms:oracle,h2
CREATE TABLE DSO_SERVICE_NEXUS_IQ_APP (
    SERVICE_ID                  NUMBER(19)      NOT NULL,
    POSITION                    NUMBER(10)      NOT NULL,
    APPLICATION                 VARCHAR2(200)   NOT NULL,
    SCAN_PATTERNS               VARCHAR2(2000),
    STAGE                       VARCHAR2(50)    DEFAULT 'build' NOT NULL,
    FAIL_ON_NETWORK_ERROR       NUMBER(1)       DEFAULT 0 NOT NULL,
    CONSTRAINT PK_DSO_SERVICE_NEXUS_IQ_APP PRIMARY KEY (SERVICE_ID, POSITION),
    CONSTRAINT FK_DSO_NEXUS_IQ_APP_SERVICE FOREIGN KEY (SERVICE_ID) REFERENCES DSO_SERVICE (ID) ON DELETE CASCADE,
    CONSTRAINT CK_DSO_NEXUS_IQ_APP_FLAGS CHECK (FAIL_ON_NETWORK_ERROR IN (0, 1))
);
INSERT INTO DSO_SERVICE_NEXUS_IQ_APP (SERVICE_ID, POSITION, APPLICATION, SCAN_PATTERNS, STAGE, FAIL_ON_NETWORK_ERROR)
SELECT ID, 0, NEXUS_IQ_APPLICATION, NEXUS_IQ_SCAN_PATTERNS, NEXUS_IQ_STAGE, NEXUS_IQ_FAIL_ON_NETWORK_ERROR
  FROM DSO_SERVICE
 WHERE NEXUS_IQ_APPLICATION IS NOT NULL;
ALTER TABLE DSO_SERVICE DROP CONSTRAINT CK_DSO_SERVICE_FLAGS;
ALTER TABLE DSO_SERVICE DROP COLUMN NEXUS_IQ_APPLICATION;
ALTER TABLE DSO_SERVICE DROP COLUMN NEXUS_IQ_SCAN_PATTERNS;
ALTER TABLE DSO_SERVICE DROP COLUMN NEXUS_IQ_STAGE;
ALTER TABLE DSO_SERVICE DROP COLUMN NEXUS_IQ_FAIL_ON_NETWORK_ERROR;
--rollback ALTER TABLE DSO_SERVICE ADD (
--rollback     NEXUS_IQ_APPLICATION                VARCHAR2(200),
--rollback     NEXUS_IQ_SCAN_PATTERNS              VARCHAR2(2000),
--rollback     NEXUS_IQ_STAGE                      VARCHAR2(50)    DEFAULT 'build' NOT NULL,
--rollback     NEXUS_IQ_FAIL_ON_NETWORK_ERROR      NUMBER(1)       DEFAULT 0 NOT NULL
--rollback );
--rollback UPDATE DSO_SERVICE s SET
--rollback     NEXUS_IQ_APPLICATION = (SELECT a.APPLICATION FROM DSO_SERVICE_NEXUS_IQ_APP a
--rollback                              WHERE a.SERVICE_ID = s.ID AND a.POSITION = 0),
--rollback     NEXUS_IQ_SCAN_PATTERNS = (SELECT a.SCAN_PATTERNS FROM DSO_SERVICE_NEXUS_IQ_APP a
--rollback                                WHERE a.SERVICE_ID = s.ID AND a.POSITION = 0),
--rollback     NEXUS_IQ_STAGE = COALESCE((SELECT a.STAGE FROM DSO_SERVICE_NEXUS_IQ_APP a
--rollback                                 WHERE a.SERVICE_ID = s.ID AND a.POSITION = 0), 'build'),
--rollback     NEXUS_IQ_FAIL_ON_NETWORK_ERROR = COALESCE((SELECT a.FAIL_ON_NETWORK_ERROR FROM DSO_SERVICE_NEXUS_IQ_APP a
--rollback                                                 WHERE a.SERVICE_ID = s.ID AND a.POSITION = 0), 0);
--rollback ALTER TABLE DSO_SERVICE ADD CONSTRAINT CK_DSO_SERVICE_FLAGS CHECK (BUILD_TOOL_AUTO_SETUP IN (0, 1) AND UNIT_TEST_ALLOW_EMPTY IN (0, 1)
--rollback     AND UCD_SKIP_WAIT IN (0, 1) AND UCD_DEPLOY_WITH_SNAPSHOT IN (0, 1) AND UCD_UPDATE_SNAPSHOT_COMPONENTS IN (0, 1)
--rollback     AND UCD_INCLUDE_ONLY_DEPLOY_VERSIONS IN (0, 1) AND UCD_DEPLOY_ONLY_CHANGED IN (0, 1)
--rollback     AND APPSCAN_COMPILE IN (0, 1) AND APPSCAN_SOURCE_CODE_ONLY IN (0, 1) AND APPSCAN_USE_CONFIG_FILE IN (0, 1)
--rollback     AND APPSCAN_INSECURE_TLS IN (0, 1) AND DAST_ENABLED IN (0, 1) AND SONAR_ADD_BADGES IN (0, 1)
--rollback     AND SONAR_FULL_BADGES IN (0, 1) AND NEXUS_IQ_FAIL_ON_NETWORK_ERROR IN (0, 1) AND GOLDEN_FIX_ENABLED IN (0, 1)
--rollback     AND GOLDEN_FIX_DIRECT_ONLY IN (0, 1) AND GOLDEN_FIX_VERIFY IN (0, 1) AND METRICS_ENABLED IN (0, 1)
--rollback     AND FLUTTER_SONAR_PLUGIN IN (0, 1));
--rollback DROP TABLE DSO_SERVICE_NEXUS_IQ_APP;

--changeset dso-portal:009-service-keys dbms:oracle,h2
ALTER TABLE DSO_SERVICE ADD (
    BUILD_LABEL                         VARCHAR2(200),
    BUILD_RETURN_STDOUT                 NUMBER(1)       DEFAULT 0 NOT NULL,
    UNIT_TEST_LABEL                     VARCHAR2(200),
    UNIT_TEST_RETURN_STDOUT             NUMBER(1)       DEFAULT 0 NOT NULL,
    SMOKE_REQUIRED                      NUMBER(1)       DEFAULT 1 NOT NULL,
    REGRESSION_REQUIRED                 NUMBER(1)       DEFAULT 1 NOT NULL,
    PERFORMANCE_REQUIRED                NUMBER(1)       DEFAULT 1 NOT NULL,
    SMOKE_POLL_INTERVAL_SEC             NUMBER(10),
    REGRESSION_POLL_INTERVAL_SEC        NUMBER(10),
    PERFORMANCE_POLL_INTERVAL_SEC       NUMBER(10),
    DELIVERY_LABEL                      VARCHAR2(200),
    DELIVERY_RETURN_STDOUT              NUMBER(1)       DEFAULT 0 NOT NULL,
    APPSCAN_COMPILE_LABEL               VARCHAR2(200),
    APPSCAN_COMPILE_RETURN_STDOUT       NUMBER(1)       DEFAULT 0 NOT NULL,
    APPSCAN_SECRET_CREDENTIALS_ID       VARCHAR2(200),
    SONAR_LABEL                         VARCHAR2(200),
    SONAR_RETURN_STDOUT                 NUMBER(1)       DEFAULT 0 NOT NULL,
    SONAR_SERVER_URL                    VARCHAR2(1000),
    NEXUS_IQ_SERVER_URL                 VARCHAR2(1000),
    NEXUS_IQ_CREDENTIALS_ID             VARCHAR2(200),
    INFLUX_URL                          VARCHAR2(1000),
    INFLUX_CREDENTIALS_ID               VARCHAR2(200)
);
ALTER TABLE DSO_SERVICE ADD CONSTRAINT CK_DSO_SERVICE_FLAGS CHECK (BUILD_TOOL_AUTO_SETUP IN (0, 1)
    AND BUILD_RETURN_STDOUT IN (0, 1) AND UNIT_TEST_ALLOW_EMPTY IN (0, 1) AND UNIT_TEST_RETURN_STDOUT IN (0, 1)
    AND SMOKE_REQUIRED IN (0, 1) AND REGRESSION_REQUIRED IN (0, 1) AND PERFORMANCE_REQUIRED IN (0, 1)
    AND DELIVERY_RETURN_STDOUT IN (0, 1) AND UCD_SKIP_WAIT IN (0, 1) AND UCD_DEPLOY_WITH_SNAPSHOT IN (0, 1)
    AND UCD_UPDATE_SNAPSHOT_COMPONENTS IN (0, 1) AND UCD_INCLUDE_ONLY_DEPLOY_VERSIONS IN (0, 1)
    AND UCD_DEPLOY_ONLY_CHANGED IN (0, 1) AND APPSCAN_COMPILE IN (0, 1) AND APPSCAN_COMPILE_RETURN_STDOUT IN (0, 1)
    AND APPSCAN_SOURCE_CODE_ONLY IN (0, 1) AND APPSCAN_USE_CONFIG_FILE IN (0, 1) AND APPSCAN_INSECURE_TLS IN (0, 1)
    AND DAST_ENABLED IN (0, 1) AND SONAR_ADD_BADGES IN (0, 1) AND SONAR_FULL_BADGES IN (0, 1)
    AND SONAR_RETURN_STDOUT IN (0, 1) AND GOLDEN_FIX_ENABLED IN (0, 1) AND GOLDEN_FIX_DIRECT_ONLY IN (0, 1)
    AND GOLDEN_FIX_VERIFY IN (0, 1) AND METRICS_ENABLED IN (0, 1) AND FLUTTER_SONAR_PLUGIN IN (0, 1));
--rollback ALTER TABLE DSO_SERVICE DROP CONSTRAINT CK_DSO_SERVICE_FLAGS;
--rollback ALTER TABLE DSO_SERVICE DROP COLUMN INFLUX_CREDENTIALS_ID;
--rollback ALTER TABLE DSO_SERVICE DROP COLUMN INFLUX_URL;
--rollback ALTER TABLE DSO_SERVICE DROP COLUMN NEXUS_IQ_CREDENTIALS_ID;
--rollback ALTER TABLE DSO_SERVICE DROP COLUMN NEXUS_IQ_SERVER_URL;
--rollback ALTER TABLE DSO_SERVICE DROP COLUMN SONAR_SERVER_URL;
--rollback ALTER TABLE DSO_SERVICE DROP COLUMN SONAR_RETURN_STDOUT;
--rollback ALTER TABLE DSO_SERVICE DROP COLUMN SONAR_LABEL;
--rollback ALTER TABLE DSO_SERVICE DROP COLUMN APPSCAN_SECRET_CREDENTIALS_ID;
--rollback ALTER TABLE DSO_SERVICE DROP COLUMN APPSCAN_COMPILE_RETURN_STDOUT;
--rollback ALTER TABLE DSO_SERVICE DROP COLUMN APPSCAN_COMPILE_LABEL;
--rollback ALTER TABLE DSO_SERVICE DROP COLUMN DELIVERY_RETURN_STDOUT;
--rollback ALTER TABLE DSO_SERVICE DROP COLUMN DELIVERY_LABEL;
--rollback ALTER TABLE DSO_SERVICE DROP COLUMN PERFORMANCE_POLL_INTERVAL_SEC;
--rollback ALTER TABLE DSO_SERVICE DROP COLUMN REGRESSION_POLL_INTERVAL_SEC;
--rollback ALTER TABLE DSO_SERVICE DROP COLUMN SMOKE_POLL_INTERVAL_SEC;
--rollback ALTER TABLE DSO_SERVICE DROP COLUMN PERFORMANCE_REQUIRED;
--rollback ALTER TABLE DSO_SERVICE DROP COLUMN REGRESSION_REQUIRED;
--rollback ALTER TABLE DSO_SERVICE DROP COLUMN SMOKE_REQUIRED;
--rollback ALTER TABLE DSO_SERVICE DROP COLUMN UNIT_TEST_RETURN_STDOUT;
--rollback ALTER TABLE DSO_SERVICE DROP COLUMN UNIT_TEST_LABEL;
--rollback ALTER TABLE DSO_SERVICE DROP COLUMN BUILD_RETURN_STDOUT;
--rollback ALTER TABLE DSO_SERVICE DROP COLUMN BUILD_LABEL;

--changeset dso-portal:009-test-job-keys dbms:oracle,h2
ALTER TABLE DSO_SERVICE_TEST_JOB ADD (
    POLL_INTERVAL_SEC                   NUMBER(10),
    TOKEN_CREDENTIALS_ID                VARCHAR2(200),
    ABORT_TRIGGERED_JOB                 NUMBER(1)       DEFAULT 0 NOT NULL,
    OVERRIDE_TRUST_ALL_CERTIFICATES     NUMBER(1)       DEFAULT 0 NOT NULL,
    PREVENT_REMOTE_BUILD_QUEUE          NUMBER(1)       DEFAULT 0 NOT NULL,
    TRUST_ALL_CERTIFICATES              NUMBER(1)       DEFAULT 0 NOT NULL,
    USE_CRUMB_CACHE                     NUMBER(1)       DEFAULT 0 NOT NULL,
    USE_JOB_INFO_CACHE                  NUMBER(1)       DEFAULT 0 NOT NULL
);
ALTER TABLE DSO_SERVICE_TEST_JOB ADD CONSTRAINT CK_DSO_TEST_JOB_FLAGS CHECK (ABORT_TRIGGERED_JOB IN (0, 1)
    AND OVERRIDE_TRUST_ALL_CERTIFICATES IN (0, 1) AND PREVENT_REMOTE_BUILD_QUEUE IN (0, 1)
    AND TRUST_ALL_CERTIFICATES IN (0, 1) AND USE_CRUMB_CACHE IN (0, 1) AND USE_JOB_INFO_CACHE IN (0, 1));
--rollback ALTER TABLE DSO_SERVICE_TEST_JOB DROP CONSTRAINT CK_DSO_TEST_JOB_FLAGS;
--rollback ALTER TABLE DSO_SERVICE_TEST_JOB DROP COLUMN USE_JOB_INFO_CACHE;
--rollback ALTER TABLE DSO_SERVICE_TEST_JOB DROP COLUMN USE_CRUMB_CACHE;
--rollback ALTER TABLE DSO_SERVICE_TEST_JOB DROP COLUMN TRUST_ALL_CERTIFICATES;
--rollback ALTER TABLE DSO_SERVICE_TEST_JOB DROP COLUMN PREVENT_REMOTE_BUILD_QUEUE;
--rollback ALTER TABLE DSO_SERVICE_TEST_JOB DROP COLUMN OVERRIDE_TRUST_ALL_CERTIFICATES;
--rollback ALTER TABLE DSO_SERVICE_TEST_JOB DROP COLUMN ABORT_TRIGGERED_JOB;
--rollback ALTER TABLE DSO_SERVICE_TEST_JOB DROP COLUMN TOKEN_CREDENTIALS_ID;
--rollback ALTER TABLE DSO_SERVICE_TEST_JOB DROP COLUMN POLL_INTERVAL_SEC;

--changeset dso-portal:009-urban-code-keys dbms:oracle,h2
ALTER TABLE DSO_UCD_APPLICATION ADD (
    SITE_NAME                           VARCHAR2(200),
    DEPLOY_PROCESS                      VARCHAR2(200),
    SKIP_WAIT                           NUMBER(1),
    DEPLOY_WITH_SNAPSHOT                NUMBER(1),
    UPDATE_SNAPSHOT_COMPONENTS          NUMBER(1),
    INCLUDE_ONLY_DEPLOY_VERSIONS        NUMBER(1),
    DEPLOY_ONLY_CHANGED                 NUMBER(1),
    DEPLOY_DESCRIPTION                  VARCHAR2(1000),
    DESCRIPTION                         VARCHAR2(1000),
    REQUEST_PROPERTIES                  VARCHAR2(2000)
);
ALTER TABLE DSO_UCD_APPLICATION ADD CONSTRAINT CK_DSO_UCD_APP_FLAGS CHECK (SKIP_WAIT IN (0, 1)
    AND DEPLOY_WITH_SNAPSHOT IN (0, 1) AND UPDATE_SNAPSHOT_COMPONENTS IN (0, 1)
    AND INCLUDE_ONLY_DEPLOY_VERSIONS IN (0, 1) AND DEPLOY_ONLY_CHANGED IN (0, 1));
ALTER TABLE DSO_UCD_COMPONENT ADD (
    EXTENSIONS                          VARCHAR2(200),
    CHARSET                             VARCHAR2(50),
    PUSH_DESCRIPTION                    VARCHAR2(1000),
    VERSION_PROPERTIES                  VARCHAR2(2000),
    VERSION_DESCRIPTION                 VARCHAR2(1000)
);
--rollback ALTER TABLE DSO_UCD_COMPONENT DROP COLUMN VERSION_DESCRIPTION;
--rollback ALTER TABLE DSO_UCD_COMPONENT DROP COLUMN VERSION_PROPERTIES;
--rollback ALTER TABLE DSO_UCD_COMPONENT DROP COLUMN PUSH_DESCRIPTION;
--rollback ALTER TABLE DSO_UCD_COMPONENT DROP COLUMN CHARSET;
--rollback ALTER TABLE DSO_UCD_COMPONENT DROP COLUMN EXTENSIONS;
--rollback ALTER TABLE DSO_UCD_APPLICATION DROP CONSTRAINT CK_DSO_UCD_APP_FLAGS;
--rollback ALTER TABLE DSO_UCD_APPLICATION DROP COLUMN REQUEST_PROPERTIES;
--rollback ALTER TABLE DSO_UCD_APPLICATION DROP COLUMN DESCRIPTION;
--rollback ALTER TABLE DSO_UCD_APPLICATION DROP COLUMN DEPLOY_DESCRIPTION;
--rollback ALTER TABLE DSO_UCD_APPLICATION DROP COLUMN DEPLOY_ONLY_CHANGED;
--rollback ALTER TABLE DSO_UCD_APPLICATION DROP COLUMN INCLUDE_ONLY_DEPLOY_VERSIONS;
--rollback ALTER TABLE DSO_UCD_APPLICATION DROP COLUMN UPDATE_SNAPSHOT_COMPONENTS;
--rollback ALTER TABLE DSO_UCD_APPLICATION DROP COLUMN DEPLOY_WITH_SNAPSHOT;
--rollback ALTER TABLE DSO_UCD_APPLICATION DROP COLUMN SKIP_WAIT;
--rollback ALTER TABLE DSO_UCD_APPLICATION DROP COLUMN DEPLOY_PROCESS;
--rollback ALTER TABLE DSO_UCD_APPLICATION DROP COLUMN SITE_NAME;

--changeset dso-portal:009-openshift-pins dbms:oracle,h2
ALTER TABLE DSO_SERVICE_OPENSHIFT_TARGET ADD (
    BUILD_TAG                           VARCHAR2(500),
    INTERNAL_DOCKER_URL                 VARCHAR2(500)
);
--rollback ALTER TABLE DSO_SERVICE_OPENSHIFT_TARGET DROP COLUMN INTERNAL_DOCKER_URL;
--rollback ALTER TABLE DSO_SERVICE_OPENSHIFT_TARGET DROP COLUMN BUILD_TAG;
