--liquibase formatted sql

--changeset dso-portal:015-nexus-iq-pipeline dbms:oracle,h2
ALTER TABLE DSO_PIPELINE DROP CONSTRAINT CK_DSO_PIPELINE_TYPE;
ALTER TABLE DSO_PIPELINE ADD CONSTRAINT CK_DSO_PIPELINE_TYPE
    CHECK (PIPELINE_TYPE IN ('FULL', 'SECURITY', 'EXTENDED', 'SAST', 'NEXUS_IQ'));
--rollback DELETE FROM DSO_PIPELINE WHERE PIPELINE_TYPE = 'NEXUS_IQ';
--rollback ALTER TABLE DSO_PIPELINE DROP CONSTRAINT CK_DSO_PIPELINE_TYPE;
--rollback ALTER TABLE DSO_PIPELINE ADD CONSTRAINT CK_DSO_PIPELINE_TYPE
--rollback     CHECK (PIPELINE_TYPE IN ('FULL', 'SECURITY', 'EXTENDED', 'SAST'));
