--liquibase formatted sql

--changeset dso-portal:022-change-task-fields dbms:oracle,h2
ALTER TABLE DSO_CHANGE_PROFILE_TASK ADD (
    ASSIGNMENT_GROUP            VARCHAR2(200),
    ASSIGNED_TO                 VARCHAR2(200),
    CONFIGURATION_ITEM          VARCHAR2(200),
    PLATFORM                    VARCHAR2(40),
    APPLICATION                 VARCHAR2(100),
    PACKAGES                    VARCHAR2(2000),
    BACKOUT_PACKAGES            VARCHAR2(2000),
    IMPORTANCE                  VARCHAR2(40),
    ADDITIONAL_COMMENTS         VARCHAR2(2000)
);
ALTER TABLE DSO_PRODUCTION_CHANGE_TASK ADD (
    ASSIGNMENT_GROUP            VARCHAR2(200),
    ASSIGNED_TO                 VARCHAR2(200),
    CONFIGURATION_ITEM          VARCHAR2(200),
    PLATFORM                    VARCHAR2(40),
    APPLICATION                 VARCHAR2(100),
    PACKAGES                    VARCHAR2(2000),
    BACKOUT_PACKAGES            VARCHAR2(2000),
    IMPORTANCE                  VARCHAR2(40),
    ADDITIONAL_COMMENTS         VARCHAR2(2000),
    TASK_START                  TIMESTAMP,
    APPROVAL                    VARCHAR2(40)
);
UPDATE DSO_CHANGE_PROFILE_TASK t SET
    ASSIGNMENT_GROUP = (SELECT p.ASSIGNMENT_GROUP FROM DSO_CHANGE_PROFILE p WHERE p.ID = t.PROFILE_ID),
    CONFIGURATION_ITEM = (SELECT p.CONFIGURATION_ITEM FROM DSO_CHANGE_PROFILE p WHERE p.ID = t.PROFILE_ID);
UPDATE DSO_PRODUCTION_CHANGE_TASK t SET
    ASSIGNMENT_GROUP = (SELECT c.ASSIGNMENT_GROUP FROM DSO_PRODUCTION_CHANGE c WHERE c.ID = t.CHANGE_ID),
    CONFIGURATION_ITEM = (SELECT c.CONFIGURATION_ITEM FROM DSO_PRODUCTION_CHANGE c WHERE c.ID = t.CHANGE_ID);
--rollback ALTER TABLE DSO_PRODUCTION_CHANGE_TASK DROP (ASSIGNMENT_GROUP, ASSIGNED_TO, CONFIGURATION_ITEM, PLATFORM, APPLICATION, PACKAGES, BACKOUT_PACKAGES, IMPORTANCE, ADDITIONAL_COMMENTS, TASK_START, APPROVAL);
--rollback ALTER TABLE DSO_CHANGE_PROFILE_TASK DROP (ASSIGNMENT_GROUP, ASSIGNED_TO, CONFIGURATION_ITEM, PLATFORM, APPLICATION, PACKAGES, BACKOUT_PACKAGES, IMPORTANCE, ADDITIONAL_COMMENTS);

--changeset dso-portal:022-change-task-state-h2 dbms:h2
ALTER TABLE DSO_PRODUCTION_CHANGE_TASK DROP CONSTRAINT CK_DSO_PRODUCTION_CHANGE_TASK_STATE;
ALTER TABLE DSO_PRODUCTION_CHANGE_TASK ADD CONSTRAINT CK_DSO_PRODUCTION_CHANGE_TASK_STATE
    CHECK (STATE IN ('OPEN', 'WORK_IN_PROGRESS', 'CLOSED', 'CANCELED'));
--rollback empty
