apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: beadle
      app.kubernetes.io/part-of: bbh-devsecops
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
configMapGenerator:
  - name: beadle-config
    literals:
      - SPRING_PROFILES_ACTIVE=rd
      - CYBERTRACK_URL=
      - CYBERTRACK_PROJECT_KEY=SCP
      - CYBERTRACK_ISSUE_TYPE=Task
