apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: beadle
spec:
  to:
    kind: Service
    name: beadle
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
