--liquibase formatted sql

--changeset dso-portal:004-bitbucket-repository dbms:oracle,h2
ALTER TABLE DSO_SERVICE ADD (
    BITBUCKET_API_URL                   VARCHAR2(1000),
    BITBUCKET_WORKSPACE                 VARCHAR2(200),
    BITBUCKET_PROJECT_KEY               VARCHAR2(200),
    BITBUCKET_REPO_SLUG                 VARCHAR2(200)
);
--rollback ALTER TABLE DSO_SERVICE DROP COLUMN BITBUCKET_REPO_SLUG;
--rollback ALTER TABLE DSO_SERVICE DROP COLUMN BITBUCKET_PROJECT_KEY;
--rollback ALTER TABLE DSO_SERVICE DROP COLUMN BITBUCKET_WORKSPACE;
--rollback ALTER TABLE DSO_SERVICE DROP COLUMN BITBUCKET_API_URL;
