--liquibase formatted sql

--changeset dso-portal:017-change-profile-wizard-fields dbms:oracle,h2
ALTER TABLE DSO_CHANGE_PROFILE ADD (
    REQUESTED_FOR               VARCHAR2(200),
    REQUESTED_BY                VARCHAR2(200),
    REQUEST_DEPARTMENT          VARCHAR2(100),
    ASSIGNED_TO                 VARCHAR2(200),
    DIRECT_BUSINESS_SERVICE     VARCHAR2(200),
    USERS_AFFECTED              VARCHAR2(2000),
    SECURE_CODING_TICKET        VARCHAR2(40)
);
--rollback ALTER TABLE DSO_CHANGE_PROFILE DROP (REQUESTED_FOR, REQUESTED_BY, REQUEST_DEPARTMENT, ASSIGNED_TO,
--rollback     DIRECT_BUSINESS_SERVICE, USERS_AFFECTED, SECURE_CODING_TICKET);

--changeset dso-portal:017-production-change-wizard-fields dbms:oracle,h2
ALTER TABLE DSO_PRODUCTION_CHANGE ADD (
    OPENED_BY                   VARCHAR2(200),
    REQUESTED_FOR               VARCHAR2(200),
    REQUESTED_BY                VARCHAR2(200),
    REQUEST_DEPARTMENT          VARCHAR2(100),
    ASSIGNED_TO                 VARCHAR2(200),
    DIRECT_BUSINESS_SERVICE     VARCHAR2(200),
    USERS_AFFECTED              VARCHAR2(2000),
    SECURE_CODING_TICKET        VARCHAR2(40),
    DOWNTIME_START              TIMESTAMP,
    DOWNTIME_END                TIMESTAMP
);
UPDATE DSO_PRODUCTION_CHANGE SET DOWNTIME_START = INSTALLATION_START, DOWNTIME_END = INSTALLATION_END
 WHERE DOWNTIME = 1;
--rollback ALTER TABLE DSO_PRODUCTION_CHANGE DROP (OPENED_BY, REQUESTED_FOR, REQUESTED_BY, REQUEST_DEPARTMENT,
--rollback     ASSIGNED_TO, DIRECT_BUSINESS_SERVICE, USERS_AFFECTED, SECURE_CODING_TICKET, DOWNTIME_START, DOWNTIME_END);

--changeset dso-portal:017-change-type-standard dbms:oracle,h2
UPDATE DSO_CHANGE_PROFILE SET CHANGE_TYPE = 'STANDARD' WHERE CHANGE_TYPE = 'NORMAL';
UPDATE DSO_PRODUCTION_CHANGE SET CHANGE_TYPE = 'STANDARD' WHERE CHANGE_TYPE = 'NORMAL';
--rollback UPDATE DSO_CHANGE_PROFILE SET CHANGE_TYPE = 'NORMAL'
--rollback  WHERE CHANGE_TYPE IN ('STANDARD', 'BUSINESS_CRITICAL', 'MODEL');
--rollback UPDATE DSO_PRODUCTION_CHANGE SET CHANGE_TYPE = 'NORMAL'
--rollback  WHERE CHANGE_TYPE IN ('STANDARD', 'BUSINESS_CRITICAL', 'MODEL');

--changeset dso-portal:017-category-list dbms:oracle,h2
UPDATE DSO_CHANGE_PROFILE SET CATEGORY = CASE UPPER(TRIM(CATEGORY))
    WHEN 'APPLICATION' THEN 'Application' WHEN 'HARDWARE' THEN 'Hardware' WHEN 'INFRASTRUCTURE' THEN 'Infrastructure'
    WHEN 'SYSTEM SOFTWARE' THEN 'System Software' WHEN 'NETWORK' THEN 'Network' WHEN 'TELECOM' THEN 'Telecom'
    WHEN 'DATA AMENDMENT' THEN 'Data Amendment' WHEN 'DESKTOP SOFTWARE' THEN 'Desktop Software'
    WHEN 'STORAGE' THEN 'Storage' WHEN 'FACILITIES' THEN 'Facilities' WHEN 'DATABASE' THEN 'Database'
    WHEN 'SOFTWARE' THEN 'Application' WHEN 'APPS' THEN 'Application' ELSE 'Other' END;
UPDATE DSO_PRODUCTION_CHANGE SET CATEGORY = CASE UPPER(TRIM(CATEGORY))
    WHEN 'APPLICATION' THEN 'Application' WHEN 'HARDWARE' THEN 'Hardware' WHEN 'INFRASTRUCTURE' THEN 'Infrastructure'
    WHEN 'SYSTEM SOFTWARE' THEN 'System Software' WHEN 'NETWORK' THEN 'Network' WHEN 'TELECOM' THEN 'Telecom'
    WHEN 'DATA AMENDMENT' THEN 'Data Amendment' WHEN 'DESKTOP SOFTWARE' THEN 'Desktop Software'
    WHEN 'STORAGE' THEN 'Storage' WHEN 'FACILITIES' THEN 'Facilities' WHEN 'DATABASE' THEN 'Database'
    WHEN 'SOFTWARE' THEN 'Application' WHEN 'APPS' THEN 'Application' ELSE 'Other' END;
--rollback empty

--changeset dso-portal:017-change-profile-risk-lists dbms:oracle,h2
ALTER TABLE DSO_CHANGE_PROFILE ADD (
    RISK_BBH_WORKGROUPS_LIST        VARCHAR2(100),
    RISK_BBH_USERS_LIST             VARCHAR2(100),
    RISK_BBH_APPLICATIONS_LIST      VARCHAR2(100),
    RISK_CLIENTS_OUTSIDE_BBH_LIST   VARCHAR2(100)
);
UPDATE DSO_CHANGE_PROFILE SET
    RISK_BBH_WORKGROUPS_LIST = CASE WHEN RISK_BBH_WORKGROUPS <= 1 THEN 'Single'
        WHEN RISK_BBH_WORKGROUPS <= 3 THEN '2-3' WHEN RISK_BBH_WORKGROUPS > 3 THEN 'More than 3' END,
    RISK_BBH_USERS_LIST = CASE WHEN RISK_BBH_USERS < 5 THEN 'Less than 5' WHEN RISK_BBH_USERS <= 25 THEN '5-25'
        WHEN RISK_BBH_USERS <= 250 THEN '26-250' WHEN RISK_BBH_USERS > 250 THEN 'All users' END,
    RISK_BBH_APPLICATIONS_LIST = CASE WHEN RISK_BBH_APPLICATIONS <= 1 THEN 'Single'
        WHEN RISK_BBH_APPLICATIONS = 2 THEN 'Two' WHEN RISK_BBH_APPLICATIONS > 2 THEN 'More than 2' END,
    RISK_CLIENTS_OUTSIDE_BBH_LIST = CASE WHEN RISK_CLIENTS_OUTSIDE_BBH = 0 THEN 'No clients'
        WHEN RISK_CLIENTS_OUTSIDE_BBH = 1 THEN 'Single' WHEN RISK_CLIENTS_OUTSIDE_BBH > 1 THEN 'More than one but not all' END,
    RISK_CHANGE_COMPLEXITY = CASE UPPER(TRIM(RISK_CHANGE_COMPLEXITY)) WHEN 'LOW' THEN 'Simple' WHEN 'SIMPLE' THEN 'Simple'
        WHEN 'MEDIUM' THEN 'Moderate' WHEN 'MODERATE' THEN 'Moderate' WHEN 'HIGH' THEN 'Very' WHEN 'VERY' THEN 'Very' END,
    RISK_VALIDATION_COMPLEXITY = CASE UPPER(TRIM(RISK_VALIDATION_COMPLEXITY)) WHEN 'LOW' THEN 'Simple'
        WHEN 'SIMPLE' THEN 'Simple' WHEN 'MEDIUM' THEN 'Moderate' WHEN 'MODERATE' THEN 'Moderate' WHEN 'HIGH' THEN 'Very'
        WHEN 'VERY' THEN 'Very' END,
    RISK_BACKOUT_TESTING = CASE UPPER(TRIM(RISK_BACKOUT_TESTING)) WHEN 'LESS THAN 30 MINUTES' THEN 'Less than 30 minutes'
        WHEN '30 MINS - 2 HOURS' THEN '30 mins - 2 hours' WHEN 'GREATER THAN 2 HOURS' THEN 'Greater than 2 hours'
        WHEN 'UNABLE TO TEST' THEN 'Unable to test' END,
    RISK_PLATFORM_STATUS = CASE WHEN UPPER(RISK_PLATFORM_STATUS) LIKE '%EXIST%' THEN 'Existing'
        WHEN UPPER(RISK_PLATFORM_STATUS) LIKE '%NEW%' THEN 'New'
        WHEN UPPER(RISK_PLATFORM_STATUS) LIKE '%DECOM%' THEN 'Decommissioned' END,
    RISK_BUSINESS_IMPACT = CASE UPPER(TRIM(RISK_BUSINESS_IMPACT)) WHEN 'NONE' THEN 'None' WHEN 'LOW' THEN 'Low'
        WHEN 'MEDIUM' THEN 'Medium' WHEN 'HIGH' THEN 'High' END;
ALTER TABLE DSO_CHANGE_PROFILE DROP (RISK_BBH_WORKGROUPS, RISK_BBH_USERS, RISK_BBH_APPLICATIONS, RISK_CLIENTS,
    RISK_CLIENTS_OUTSIDE_BBH);
ALTER TABLE DSO_CHANGE_PROFILE RENAME COLUMN RISK_BBH_WORKGROUPS_LIST TO RISK_BBH_WORKGROUPS;
ALTER TABLE DSO_CHANGE_PROFILE RENAME COLUMN RISK_BBH_USERS_LIST TO RISK_BBH_USERS;
ALTER TABLE DSO_CHANGE_PROFILE RENAME COLUMN RISK_BBH_APPLICATIONS_LIST TO RISK_BBH_APPLICATIONS;
ALTER TABLE DSO_CHANGE_PROFILE RENAME COLUMN RISK_CLIENTS_OUTSIDE_BBH_LIST TO RISK_CLIENTS_OUTSIDE_BBH;
--rollback ALTER TABLE DSO_CHANGE_PROFILE ADD (
--rollback     RISK_BBH_WORKGROUPS_NUMBER      NUMBER(10),
--rollback     RISK_BBH_USERS_NUMBER           NUMBER(10),
--rollback     RISK_BBH_APPLICATIONS_NUMBER    NUMBER(10),
--rollback     RISK_CLIENTS                    NUMBER(10),
--rollback     RISK_CLIENTS_OUTSIDE_BBH_NUMBER NUMBER(10)
--rollback );
--rollback UPDATE DSO_CHANGE_PROFILE SET
--rollback     RISK_BBH_WORKGROUPS_NUMBER = CASE RISK_BBH_WORKGROUPS WHEN 'Single' THEN 1 WHEN '2-3' THEN 2
--rollback         WHEN 'More than 3' THEN 4 END,
--rollback     RISK_BBH_USERS_NUMBER = CASE RISK_BBH_USERS WHEN 'Less than 5' THEN 1 WHEN '5-25' THEN 5
--rollback         WHEN '26-250' THEN 26 WHEN 'All users' THEN 251 END,
--rollback     RISK_BBH_APPLICATIONS_NUMBER = CASE RISK_BBH_APPLICATIONS WHEN 'Single' THEN 1 WHEN 'Two' THEN 2
--rollback         WHEN 'More than 2' THEN 3 END,
--rollback     RISK_CLIENTS_OUTSIDE_BBH_NUMBER = CASE RISK_CLIENTS_OUTSIDE_BBH WHEN 'No clients' THEN 0 WHEN 'Single' THEN 1
--rollback         WHEN 'More than one but not all' THEN 2 WHEN 'All clients' THEN 3 END,
--rollback     RISK_CHANGE_COMPLEXITY = CASE RISK_CHANGE_COMPLEXITY WHEN 'Simple' THEN 'Low' WHEN 'Moderate' THEN 'Medium'
--rollback         WHEN 'Very' THEN 'High' END,
--rollback     RISK_VALIDATION_COMPLEXITY = CASE RISK_VALIDATION_COMPLEXITY WHEN 'Simple' THEN 'Low'
--rollback         WHEN 'Moderate' THEN 'Medium' WHEN 'Very' THEN 'High' END;
--rollback ALTER TABLE DSO_CHANGE_PROFILE DROP (RISK_BBH_WORKGROUPS, RISK_BBH_USERS, RISK_BBH_APPLICATIONS,
--rollback     RISK_CLIENTS_OUTSIDE_BBH);
--rollback ALTER TABLE DSO_CHANGE_PROFILE RENAME COLUMN RISK_BBH_WORKGROUPS_NUMBER TO RISK_BBH_WORKGROUPS;
--rollback ALTER TABLE DSO_CHANGE_PROFILE RENAME COLUMN RISK_BBH_USERS_NUMBER TO RISK_BBH_USERS;
--rollback ALTER TABLE DSO_CHANGE_PROFILE RENAME COLUMN RISK_BBH_APPLICATIONS_NUMBER TO RISK_BBH_APPLICATIONS;
--rollback ALTER TABLE DSO_CHANGE_PROFILE RENAME COLUMN RISK_CLIENTS_OUTSIDE_BBH_NUMBER TO RISK_CLIENTS_OUTSIDE_BBH;

--changeset dso-portal:017-production-change-risk-lists dbms:oracle,h2
ALTER TABLE DSO_PRODUCTION_CHANGE ADD (
    RISK_BBH_WORKGROUPS_LIST        VARCHAR2(100),
    RISK_BBH_USERS_LIST             VARCHAR2(100),
    RISK_BBH_APPLICATIONS_LIST      VARCHAR2(100),
    RISK_CLIENTS_OUTSIDE_BBH_LIST   VARCHAR2(100)
);
UPDATE DSO_PRODUCTION_CHANGE SET
    RISK_BBH_WORKGROUPS_LIST = CASE WHEN RISK_BBH_WORKGROUPS <= 1 THEN 'Single'
        WHEN RISK_BBH_WORKGROUPS <= 3 THEN '2-3' WHEN RISK_BBH_WORKGROUPS > 3 THEN 'More than 3' END,
    RISK_BBH_USERS_LIST = CASE WHEN RISK_BBH_USERS < 5 THEN 'Less than 5' WHEN RISK_BBH_USERS <= 25 THEN '5-25'
        WHEN RISK_BBH_USERS <= 250 THEN '26-250' WHEN RISK_BBH_USERS > 250 THEN 'All users' END,
    RISK_BBH_APPLICATIONS_LIST = CASE WHEN RISK_BBH_APPLICATIONS <= 1 THEN 'Single'
        WHEN RISK_BBH_APPLICATIONS = 2 THEN 'Two' WHEN RISK_BBH_APPLICATIONS > 2 THEN 'More than 2' END,
    RISK_CLIENTS_OUTSIDE_BBH_LIST = CASE WHEN RISK_CLIENTS_OUTSIDE_BBH = 0 THEN 'No clients'
        WHEN RISK_CLIENTS_OUTSIDE_BBH = 1 THEN 'Single' WHEN RISK_CLIENTS_OUTSIDE_BBH > 1 THEN 'More than one but not all' END,
    RISK_CHANGE_COMPLEXITY = CASE UPPER(TRIM(RISK_CHANGE_COMPLEXITY)) WHEN 'LOW' THEN 'Simple' WHEN 'SIMPLE' THEN 'Simple'
        WHEN 'MEDIUM' THEN 'Moderate' WHEN 'MODERATE' THEN 'Moderate' WHEN 'HIGH' THEN 'Very' WHEN 'VERY' THEN 'Very' END,
    RISK_VALIDATION_COMPLEXITY = CASE UPPER(TRIM(RISK_VALIDATION_COMPLEXITY)) WHEN 'LOW' THEN 'Simple'
        WHEN 'SIMPLE' THEN 'Simple' WHEN 'MEDIUM' THEN 'Moderate' WHEN 'MODERATE' THEN 'Moderate' WHEN 'HIGH' THEN 'Very'
        WHEN 'VERY' THEN 'Very' END,
    RISK_BACKOUT_TESTING = CASE UPPER(TRIM(RISK_BACKOUT_TESTING)) WHEN 'LESS THAN 30 MINUTES' THEN 'Less than 30 minutes'
        WHEN '30 MINS - 2 HOURS' THEN '30 mins - 2 hours' WHEN 'GREATER THAN 2 HOURS' THEN 'Greater than 2 hours'
        WHEN 'UNABLE TO TEST' THEN 'Unable to test' END,
    RISK_PLATFORM_STATUS = CASE WHEN UPPER(RISK_PLATFORM_STATUS) LIKE '%EXIST%' THEN 'Existing'
        WHEN UPPER(RISK_PLATFORM_STATUS) LIKE '%NEW%' THEN 'New'
        WHEN UPPER(RISK_PLATFORM_STATUS) LIKE '%DECOM%' THEN 'Decommissioned' END,
    RISK_BUSINESS_IMPACT = CASE UPPER(TRIM(RISK_BUSINESS_IMPACT)) WHEN 'NONE' THEN 'None' WHEN 'LOW' THEN 'Low'
        WHEN 'MEDIUM' THEN 'Medium' WHEN 'HIGH' THEN 'High' END;
ALTER TABLE DSO_PRODUCTION_CHANGE DROP (RISK_BBH_WORKGROUPS, RISK_BBH_USERS, RISK_BBH_APPLICATIONS, RISK_CLIENTS,
    RISK_CLIENTS_OUTSIDE_BBH);
ALTER TABLE DSO_PRODUCTION_CHANGE RENAME COLUMN RISK_BBH_WORKGROUPS_LIST TO RISK_BBH_WORKGROUPS;
ALTER TABLE DSO_PRODUCTION_CHANGE RENAME COLUMN RISK_BBH_USERS_LIST TO RISK_BBH_USERS;
ALTER TABLE DSO_PRODUCTION_CHANGE RENAME COLUMN RISK_BBH_APPLICATIONS_LIST TO RISK_BBH_APPLICATIONS;
ALTER TABLE DSO_PRODUCTION_CHANGE RENAME COLUMN RISK_CLIENTS_OUTSIDE_BBH_LIST TO RISK_CLIENTS_OUTSIDE_BBH;
--rollback ALTER TABLE DSO_PRODUCTION_CHANGE ADD (
--rollback     RISK_BBH_WORKGROUPS_NUMBER      NUMBER(10),
--rollback     RISK_BBH_USERS_NUMBER           NUMBER(10),
--rollback     RISK_BBH_APPLICATIONS_NUMBER    NUMBER(10),
--rollback     RISK_CLIENTS                    NUMBER(10),
--rollback     RISK_CLIENTS_OUTSIDE_BBH_NUMBER NUMBER(10)
--rollback );
--rollback UPDATE DSO_PRODUCTION_CHANGE SET
--rollback     RISK_BBH_WORKGROUPS_NUMBER = CASE RISK_BBH_WORKGROUPS WHEN 'Single' THEN 1 WHEN '2-3' THEN 2
--rollback         WHEN 'More than 3' THEN 4 END,
--rollback     RISK_BBH_USERS_NUMBER = CASE RISK_BBH_USERS WHEN 'Less than 5' THEN 1 WHEN '5-25' THEN 5
--rollback         WHEN '26-250' THEN 26 WHEN 'All users' THEN 251 END,
--rollback     RISK_BBH_APPLICATIONS_NUMBER = CASE RISK_BBH_APPLICATIONS WHEN 'Single' THEN 1 WHEN 'Two' THEN 2
--rollback         WHEN 'More than 2' THEN 3 END,
--rollback     RISK_CLIENTS_OUTSIDE_BBH_NUMBER = CASE RISK_CLIENTS_OUTSIDE_BBH WHEN 'No clients' THEN 0 WHEN 'Single' THEN 1
--rollback         WHEN 'More than one but not all' THEN 2 WHEN 'All clients' THEN 3 END,
--rollback     RISK_CHANGE_COMPLEXITY = CASE RISK_CHANGE_COMPLEXITY WHEN 'Simple' THEN 'Low' WHEN 'Moderate' THEN 'Medium'
--rollback         WHEN 'Very' THEN 'High' END,
--rollback     RISK_VALIDATION_COMPLEXITY = CASE RISK_VALIDATION_COMPLEXITY WHEN 'Simple' THEN 'Low'
--rollback         WHEN 'Moderate' THEN 'Medium' WHEN 'Very' THEN 'High' END;
--rollback ALTER TABLE DSO_PRODUCTION_CHANGE DROP (RISK_BBH_WORKGROUPS, RISK_BBH_USERS, RISK_BBH_APPLICATIONS,
--rollback     RISK_CLIENTS_OUTSIDE_BBH);
--rollback ALTER TABLE DSO_PRODUCTION_CHANGE RENAME COLUMN RISK_BBH_WORKGROUPS_NUMBER TO RISK_BBH_WORKGROUPS;
--rollback ALTER TABLE DSO_PRODUCTION_CHANGE RENAME COLUMN RISK_BBH_USERS_NUMBER TO RISK_BBH_USERS;
--rollback ALTER TABLE DSO_PRODUCTION_CHANGE RENAME COLUMN RISK_BBH_APPLICATIONS_NUMBER TO RISK_BBH_APPLICATIONS;
--rollback ALTER TABLE DSO_PRODUCTION_CHANGE RENAME COLUMN RISK_CLIENTS_OUTSIDE_BBH_NUMBER TO RISK_CLIENTS_OUTSIDE_BBH;
