--liquibase formatted sql

--changeset beadle:026-drop-portal-tables dbms:oracle,h2
DROP TABLE DSO_PIPELINE_KEY;
DROP TABLE DSO_PIPELINE;
DROP TABLE DSO_SERVICE_NEXUS_IQ_APP;
DROP TABLE DSO_UCD_COMPONENT;
DROP TABLE DSO_UCD_APPLICATION;
DROP TABLE DSO_SERVICE_OPENSHIFT_TARGET;
DROP TABLE DSO_SERVICE_SSH_TARGET;
DROP TABLE DSO_SERVICE_TEST_JOB;
DROP TABLE DSO_SERVICE;
DROP TABLE DSO_GLOBAL_SEVERITY_LIMIT;
DROP TABLE DSO_GLOBAL_SETTINGS;
DROP TABLE DSO_SERVICE_TEMPLATE;
--rollback empty

--changeset beadle:026-drop-local-metrics dbms:h2
DROP TABLE DSO_METRIC_POINT;
--rollback empty

--changeset beadle:026-product-details-only dbms:oracle,h2
ALTER TABLE DSO_PRODUCT DROP COLUMN DESCRIPTION;
ALTER TABLE DSO_PRODUCT DROP COLUMN ASOC_KEY_ID;
ALTER TABLE DSO_PRODUCT DROP COLUMN ASOC_SECRET_CREDENTIALS_ID;
--rollback empty
