--liquibase formatted sql

--changeset beadle:027-support-approver dbms:oracle,h2
ALTER TABLE DSO_CHANGE_PROFILE ADD (SUPPORT_APPROVER VARCHAR2(200));
ALTER TABLE DSO_PRODUCTION_CHANGE ADD (SUPPORT_APPROVER VARCHAR2(200));
--rollback ALTER TABLE DSO_PRODUCTION_CHANGE DROP COLUMN SUPPORT_APPROVER;
--rollback ALTER TABLE DSO_CHANGE_PROFILE DROP COLUMN SUPPORT_APPROVER;

--changeset beadle:027-support-approval-stage dbms:oracle,h2
ALTER TABLE DSO_PRODUCTION_CHANGE DROP CONSTRAINT CK_DSO_PRODUCTION_CHANGE_STATE;
ALTER TABLE DSO_PRODUCTION_CHANGE ADD CONSTRAINT CK_DSO_PRODUCTION_CHANGE_STATE CHECK (STATE IN ('DRAFT',
    'BUSINESS_APPROVAL', 'PRIMARY_APPROVAL', 'SECONDARY_APPROVAL', 'SUPPORT_APPROVAL', 'CTASK_APPROVAL',
    'ESCALATED_APPROVAL', 'IMPLEMENTATION', 'CLOSED'));
ALTER TABLE DSO_PRODUCTION_CHANGE_STAGE DROP CONSTRAINT CK_DSO_PRODUCTION_CHANGE_STAGE;
ALTER TABLE DSO_PRODUCTION_CHANGE_STAGE ADD CONSTRAINT CK_DSO_PRODUCTION_CHANGE_STAGE CHECK (STAGE IN ('DRAFT',
    'BUSINESS_APPROVAL', 'PRIMARY_APPROVAL', 'SECONDARY_APPROVAL', 'SUPPORT_APPROVAL', 'CTASK_APPROVAL',
    'ESCALATED_APPROVAL', 'IMPLEMENTATION', 'CLOSED'));
--rollback ALTER TABLE DSO_PRODUCTION_CHANGE_STAGE DROP CONSTRAINT CK_DSO_PRODUCTION_CHANGE_STAGE;
--rollback ALTER TABLE DSO_PRODUCTION_CHANGE_STAGE ADD CONSTRAINT CK_DSO_PRODUCTION_CHANGE_STAGE CHECK (STAGE IN ('DRAFT',
--rollback     'BUSINESS_APPROVAL', 'PRIMARY_APPROVAL', 'SECONDARY_APPROVAL', 'CTASK_APPROVAL', 'ESCALATED_APPROVAL',
--rollback     'IMPLEMENTATION', 'CLOSED'));
--rollback ALTER TABLE DSO_PRODUCTION_CHANGE DROP CONSTRAINT CK_DSO_PRODUCTION_CHANGE_STATE;
--rollback ALTER TABLE DSO_PRODUCTION_CHANGE ADD CONSTRAINT CK_DSO_PRODUCTION_CHANGE_STATE CHECK (STATE IN ('DRAFT',
--rollback     'BUSINESS_APPROVAL', 'PRIMARY_APPROVAL', 'SECONDARY_APPROVAL', 'CTASK_APPROVAL', 'ESCALATED_APPROVAL',
--rollback     'IMPLEMENTATION', 'CLOSED'));

--changeset beadle:027-change-approval dbms:oracle,h2
CREATE TABLE DSO_PRODUCTION_CHANGE_APPROVAL (
    CHANGE_ID                   NUMBER(19)      NOT NULL,
    POSITION                    NUMBER(10)      NOT NULL,
    APPROVAL_ROLE               VARCHAR2(20)    NOT NULL,
    APPROVER                    VARCHAR2(200),
    APPROVAL_STATE              VARCHAR2(20)    DEFAULT 'NOT_APPROVED' NOT NULL,
    REMINDER_SENT_AT            TIMESTAMP,
    REMINDER_SENT_TO            VARCHAR2(2000),
    CONSTRAINT PK_DSO_PRODUCTION_CHANGE_APPROVAL PRIMARY KEY (CHANGE_ID, POSITION),
    CONSTRAINT FK_DSO_PRODUCTION_CHANGE_APPROVAL FOREIGN KEY (CHANGE_ID)
        REFERENCES DSO_PRODUCTION_CHANGE (ID) ON DELETE CASCADE,
    CONSTRAINT CK_DSO_PRODUCTION_CHANGE_APPROVAL_ROLE CHECK (APPROVAL_ROLE IN ('BUSINESS', 'L1', 'L2', 'SUPPORT')),
    CONSTRAINT CK_DSO_PRODUCTION_CHANGE_APPROVAL_STATE
        CHECK (APPROVAL_STATE IN ('NOT_APPROVED', 'REQUESTED', 'APPROVED'))
);
INSERT INTO DSO_PRODUCTION_CHANGE_APPROVAL (CHANGE_ID, POSITION, APPROVAL_ROLE, APPROVER, APPROVAL_STATE)
SELECT c.ID, r.POSITION, r.APPROVAL_ROLE,
       CASE r.APPROVAL_ROLE WHEN 'BUSINESS' THEN c.BUSINESS_APPROVER WHEN 'L1' THEN c.L1_MANAGER
                            WHEN 'L2' THEN c.L2_MANAGER END,
       CASE WHEN s.REACHED > r.STAGE THEN 'APPROVED' WHEN s.REACHED = r.STAGE THEN 'REQUESTED'
            ELSE 'NOT_APPROVED' END
  FROM DSO_PRODUCTION_CHANGE c
  JOIN (SELECT 'DRAFT' STATE, 0 REACHED FROM DUAL
        UNION ALL SELECT 'BUSINESS_APPROVAL', 1 FROM DUAL
        UNION ALL SELECT 'PRIMARY_APPROVAL', 2 FROM DUAL
        UNION ALL SELECT 'SECONDARY_APPROVAL', 3 FROM DUAL
        UNION ALL SELECT 'SUPPORT_APPROVAL', 4 FROM DUAL
        UNION ALL SELECT 'CTASK_APPROVAL', 5 FROM DUAL
        UNION ALL SELECT 'ESCALATED_APPROVAL', 6 FROM DUAL
        UNION ALL SELECT 'IMPLEMENTATION', 7 FROM DUAL
        UNION ALL SELECT 'CLOSED', 8 FROM DUAL) s ON s.STATE = c.STATE
 CROSS JOIN (SELECT 0 POSITION, 'BUSINESS' APPROVAL_ROLE, 1 STAGE FROM DUAL
             UNION ALL SELECT 1, 'L1', 2 FROM DUAL
             UNION ALL SELECT 2, 'L2', 3 FROM DUAL
             UNION ALL SELECT 3, 'SUPPORT', 4 FROM DUAL) r;
--rollback DROP TABLE DSO_PRODUCTION_CHANGE_APPROVAL;

--changeset beadle:027-change-task-approval dbms:oracle,h2
ALTER TABLE DSO_PRODUCTION_CHANGE_TASK ADD (
    APPROVERS                   VARCHAR2(2000),
    REMINDER_SENT_AT            TIMESTAMP,
    REMINDER_SENT_TO            VARCHAR2(2000)
);
UPDATE DSO_PRODUCTION_CHANGE_TASK SET APPROVAL = CASE APPROVAL WHEN 'Approved' THEN 'APPROVED'
    WHEN 'Requested' THEN 'REQUESTED' ELSE 'NOT_APPROVED' END;
ALTER TABLE DSO_PRODUCTION_CHANGE_TASK ADD CONSTRAINT CK_DSO_PRODUCTION_CHANGE_TASK_APPROVAL
    CHECK (APPROVAL IN ('NOT_APPROVED', 'REQUESTED', 'APPROVED'));
--rollback ALTER TABLE DSO_PRODUCTION_CHANGE_TASK DROP CONSTRAINT CK_DSO_PRODUCTION_CHANGE_TASK_APPROVAL;
--rollback UPDATE DSO_PRODUCTION_CHANGE_TASK SET APPROVAL = CASE APPROVAL WHEN 'APPROVED' THEN 'Approved'
--rollback     WHEN 'REQUESTED' THEN 'Requested' ELSE 'Not Yet Requested' END;
--rollback ALTER TABLE DSO_PRODUCTION_CHANGE_TASK DROP (APPROVERS, REMINDER_SENT_AT, REMINDER_SENT_TO);

--changeset beadle:027-change-flags-h2 dbms:h2
ALTER TABLE DSO_CHANGE_PROFILE DROP CONSTRAINT CK_DSO_CHANGE_PROFILE_FLAGS;
ALTER TABLE DSO_CHANGE_PROFILE ADD CONSTRAINT CK_DSO_CHANGE_PROFILE_FLAGS
    CHECK (DOWNTIME IN (0, 1) AND PRIVILEGED_ACCESS_REQUIRED IN (0, 1));
ALTER TABLE DSO_PRODUCTION_CHANGE DROP CONSTRAINT CK_DSO_PRODUCTION_CHANGE_FLAGS;
ALTER TABLE DSO_PRODUCTION_CHANGE ADD CONSTRAINT CK_DSO_PRODUCTION_CHANGE_FLAGS
    CHECK (DOWNTIME IN (0, 1) AND PRIVILEGED_ACCESS_REQUIRED IN (0, 1));
--rollback empty
