--liquibase formatted sql

--changeset dso-portal:026-drop-beadle-tables dbms:oracle,h2
DROP TABLE DSO_PRODUCTION_CHANGE_STAGE;
DROP TABLE DSO_PRODUCTION_CHANGE_PRIVILEGED_USER;
DROP TABLE DSO_PRODUCTION_CHANGE_TASK;
DROP TABLE DSO_PRODUCTION_CHANGE;
DROP TABLE DSO_CHANGE_PROFILE_PRIVILEGED_USER;
DROP TABLE DSO_CHANGE_PROFILE_TASK;
DROP TABLE DSO_CHANGE_PROFILE;
--rollback empty

--changeset dso-portal:026-drop-local-metrics dbms:h2
DROP TABLE DSO_METRIC_POINT;
--rollback empty
